### ISSUE TITLE
Any code?

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#1]
Any code coming soon on this repo?

**Comment by kum-deepak** [comment]
Yes, very soon!

**Comment by pantonis** [comment]
!!

**Comment by sjmf** [comment]
Hooraaay~ ! 

Thanks @kum-deepak for putting this together.

**Comment by kum-deepak** [comment]
Closing this ticket, please test the code out and open tickets as needed. Thanks!
