### ISSUE TITLE
SockJS support?

### ISSUE THREAD

**Issue by ganeshkantu** [stomp-js/ng2-stompjs#10]
Very interested in porting my stompjs implementation over to use this lib. I am using it with SockJS like this:

```
        var socket = new SockJS(this.stompEndpoint);
        this.stompClient = Stomp.over(socket);
        this.stompClient.connect({}, function (frame) {}
```

I see from the examples that the `url` used is a standard web-socket. Can I use SockJS with this in any way? If so, any pointers would help me a lot!

**Comment by kum-deepak** [comment]
If you are using Angular2/4 (this library only supports Angular2/4) you can use this.

If your application is not Angular2/4, you most probably need https://github.com/stomp-js/stomp-websocket which is maintained version of the original stompjs. It supports automatic re-connection and supports SockJS out of the box.

As of now it will not work with SockJS, it can be extended to support SockJS. I would like to understand the following:

- Which server are you using?
- Which browser versions you are intending to support?

**Comment by ganeshkantu** [comment]
I am using [https://github.com/stomp-js/stomp-websocket](https://github.com/stomp-js/stomp-websocket). Using it with NG 4/CLI.

Server: Grails (Spring STOMP websocket)
Browsers: Firefox 52+, Chrome 58+, IE 11

**Comment by kum-deepak** [comment]
Give me few days.

**Comment by kum-deepak** [comment]
Created a branch sockjs. Please try it out:

- Using it with yarn
```
$ yarn add 'https://github.com/stomp-js/ng2-stompjs.git#sockjs'
```
- Using it with npm
```
$ npm install 'https://github.com/stomp-js/ng2-stompjs.git#sockjs' --save
```

Usage instruction at: https://github.com/stomp-js/ng2-stompjs/blob/sockjs/SockJS.md and a sample
project at https://github.com/stomp-js/ng4-stompjs-demo/tree/sockjs

**Comment by ganeshkantu** [comment]
Awesome. I am testing with this. Will revert back with issues if any.

**Comment by Igor-G** [comment]
Is there a possibility this branch to be merged to master soon? We are in need of it and we have a very similar setup (Spring STOMP websocket)

**Comment by kum-deepak** [comment]
Waiting for someone to confirm that it works, please let me know if you have tested and found working.

**Comment by be4code** [comment]
We are using version from SockJS branch and it works properly :)

**Comment by kum-deepak** [comment]
Merged into master and updated documentation. Will push the npm bundle soon.

**Comment by kum-deepak** [comment]
Published to npm and taggeg in github.
