### ISSUE TITLE
Angular 7 compatibility

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#102]
Which version of stomp-js/ng2-stompjs is compatible with angular 7?

Thanks

**Comment by kum-deepak** [comment]
Not tested yet, did you test any?

**Comment by pantonis** [comment]
No. I am about to upgrade to ng7 and was wondering if latest version is compatible with it.

**Comment by kum-deepak** [comment]
I have released 7.0.0-beta.3 which is now feature complete. It has a compatibility mode, so, it should work out of the box. Compatibility mode does not expose newer features. Documentation for newer version is incomplete as of now.

I have tested and written a fresh guide with instructions to use this version with Angular 7. I will love your feedback.

https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html

My next target is working on the documentation. Meanwhile https://stomp-js.github.io/rx-stomp/classes/RxStomp.html is the best place.

**Comment by kum-deepak** [comment]
I have released 7.0.0-beta.4 which is feature complete and no known issues.

Migration guide at: https://stomp-js.github.io/guide/ng2-stompjs/2018/11/05/migrate-ng2-stompjs-v7.html

Tutorial at: https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html

Based on your feedback with release it as final. 😄

**Comment by kum-deepak** [comment]
Version 7.0.0 has been released.

**Comment by pantonis** [comment]
kudos to Deepak and the contributors. Great work. Thanks a lot for maintaining this library.
