### ISSUE TITLE
Thread found while downloading the source code

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#105]
When I download source code from github, windows defender complains that a thread was found 

![image](https://user-images.githubusercontent.com/3295086/48616540-980da080-e99c-11e8-977a-d962677be02a.png)

![image](https://user-images.githubusercontent.com/3295086/48616672-f33f9300-e99c-11e8-9709-3fddbc9e8743.png)

**Comment by kum-deepak** [comment]
Scanned https://github.com/stomp-js/ng2-stompjs/archive/7.0.0.zip as well as just the UMD file using https://www.virustotal.com/

It shows clean. I do not use Windows, so, not sure what may be the issue.

**Comment by pantonis** [comment]
I tried download it through another PC seems ok. Dont know something must be wrong with the windows defender on my pc
