### ISSUE TITLE
Url deal with hostname

### ISSUE THREAD

**Issue by AndriiSiuta** [stomp-js/ng2-stompjs#107]
Hi, i just try to configure url: smth like `url: ws://window.location.host/ws`. But /ws at the end of string is ignoring by the library. I need it for flexible delpoyin on other servers.

**Comment by kum-deepak** [comment]
Not entire clear what is the issue. Please send sample code snippet.

**Comment by AndriiSiuta** [comment]
- `export const stompConfigProd: StompConfig = {
  ...stompConfig,
  url: (() => new URL(`ws://${window.location.host}/ws`))
};`

- after i write this, or => `ws://${window.location.host}/ws`, without new URL, and start application i get nothing.

**Comment by kum-deepak** [comment]
Which version of library are you using?
It will be helpful if you can send a sample project.

BTW, we use URLs from configuration files which have domain names.

**Comment by AndriiSiuta** [comment]
Can't share the project because he is private. 
package.json: "@stomp/ng2-stompjs": "^6.1.0-beta.4".

**Comment by AndriiSiuta** [comment]
Thx a lot it works!
