### ISSUE TITLE
StompConfigService removal.

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#12]
Hi,

I just updated to 0.4.1 and saw that StompConfigService was removed. I have seen the demo and the configuration is hard coded into app.module.ts. This does not cause any problem as the service is initialized without any race conditions.

In a real life application configurations are in json files. How can I wait until loading of configs is done and then initialize the StompService(s) using angular dependency injection?

Thanks

**Comment by kum-deepak** [comment]
Angular2 has a special dependency token `APP_INITIALIZER`. Any function can be registered. This function need to return a Promise, Angular initialization process will wait till this promise is fulfilled. This mechanism can be used to load any config settings. A slightly outdated example at https://gist.github.com/fernandohu/122e88c3bcd210bbe41c608c36306db9

Please check this demo https://github.com/stomp-js/ng2-stompjs-demo - in this it uses https://github.com/ngx-config/http-loader which internally uses `APP_INITIALIZER`. It is easier to comprehend than using `APP_INITIALIZER` directly.

Actually you can use this technique to fetch any configuration settings (not just for this service).

**Comment by pantonis** [comment]
APP_INITALIAZER works for eager load modules. What is the alternative way of loading config for lazy load modules?

Thanks

**Comment by kum-deepak** [comment]
In most angular applications actual loading of a lazy loaded module will either immediately follow the initial application load or will get triggered on a route being followed. In either of these cases loading configuration at the start, using APP_INITIALIZER, will keep things simple and avoid potential race conditions.

We have multiple modules in our applications which need their own configurations. We load the entire configuration - all of the modules - in a single HTTP call. Then we keep using a part for each of the modules. Our actual code is very similar to the one in the demo. 

So for example our config looks like:

```
{
  "stomp": {
    "url": "ws://127.0.0.1:15674/ws",
    "headers": {
      "login": "guest",
      "passcode": "guest"
    },
    "heartbeat_in": 0,
    "heartbeat_out": 20000,
    "reconnect_delay": 5000,
    "debug": true
  },
  "image_server": {
    "host": "img03.krinfo.net",
    "key": "SECRET"
  },
  "comment_service": {
    "host": "comments.krinfo.net",
    "key": "SECRET",
    "pub_id": "<UUID>"
  },
  "admin": {
    "soft_limits": true,
    "sites" : 18,
    "payment_status": true
  }
}
```

**Comment by pantonis** [comment]
Yes indeed you are right but there is one flaw to this design. A module configuration is available to all modules. This shouldnt cause any issues apart from security and isolation concerns. But I agree there is not anneasy alternative way to do what I asked. One way is for angular to have MODULE_INITIALIZER like they implemented APP_INITIALIZER.  I am sure that since angular is implemented this way with lazy load modules and components MODULE_INITIALIZER would be a good option :)

**Comment by kum-deepak** [comment]
Yes, you are correct :) At least they have APP_INITIALIZER now. 

It is really surprising how little documentation is available for APP_INITIALIZER.

**Comment by pantonis** [comment]
Yes I know. No documentation at all just a neat statement!
