### ISSUE TITLE
how to stop auto web-socket connection and do it manually

### ISSUE THREAD

**Issue by zymr-keshav** [stomp-js/ng2-stompjs#121]
[In your example,](https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html) WebSocket connection is done automatically. I want to call before connect and other things also mentioned the same that "In this sample, STOMP broker is connected during the Angular DI class initialization phase"

How to call the connection manually in one of my components as soon as that component getting loaded in the page.

can we have sample example?

**Comment by kum-deepak** [comment]
I will write an example soon. Meanwhile please see https://github.com/stomp-js/rx-stomp/issues/495

**Comment by zymr-keshav** [comment]
Thank you, Deepak.  one more thing I want to know. this implementation works fine but whenever page reloaded, WebSocket connection established again so I lost the previous data of the previous topic/channel. How can I persist the connection?

 I wanted to utilize [ beforeConnect ](https://stomp-js.github.io/api-docs/latest/classes/Client.html#beforeConnect)or `onConnect` method but how do I use those? they are not the part of rxStompservice?
 I have import these many in my component

```ts
mport { Message, Frame, Client } from '@stomp/stompjs';
import { RxStompService, InjectableRxStompConfig } from '@stomp/ng2-stompjs';
import { RxStompState } from '@stomp/rx-stomp';
```

I know the above method are part of `Client` import but how to use? I tried this way

`client = new Client();`

then later

```typecript
this.client.onConnect(  (cb: Frame) => {
            console.log('called on Connect', {cb});
        });
```
 but throw error: Argument of type '(cb: Frame) => void' is not assignable to parameter of type 'Frame'.
  Property 'command' is missing in type '(cb: Frame) => void'.

**Comment by kum-deepak** [comment]
[RxStompService](https://stomp-js.github.io/api-docs/latest/injectables/RxStompService.html) extends [RxStomp](https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html) and [InjectableRxStompConfig](https://stomp-js.github.io/api-docs/latest/injectables/InjectableRxStompConfig.html) extends [RxStompConfig](https://stomp-js.github.io/api-docs/latest/classes/RxStompConfig.html).

So, simplly add  `beforeConnect` to your config. Please check https://stomp-js.github.io/api-docs/latest/classes/RxStompConfig.html#beforeConnect.

Please note that https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#configure can be called multiple times.

**Comment by zymr-keshav** [comment]
But there is no such method as `onConnect` in `RxStompConfig` but available in `Client`

**Comment by kum-deepak** [comment]
Please change your code as follows and try:

```typescript
import { RxStompService, InjectableRxStompConfig } from '@stomp/ng2-stompjs';
export class NotificationComponent implements OnInit, OnDestroy, AfterContentInit {
    constructor(
        private rxStompService: RxStompService,
        private rxStompConfig: InjectableRxStompConfig
    ) {}

    ngAfterContentInit() {
        this.initStomp();
    }

    private initStomp() {
        // Replace if still needed
        // this.checkConnection();
        const stompConfig: InjectableRxStompConfig = Object.assign({}, myRxStompConfig, {
            connectHeaders: {
                access_token: sessionStorage.getItem('token')
            },
            beforeConnect: () => {
                console.log('%c called before connect', 'color: blue');
            }
        });

        this.rxStompService.configure(stompConfig);
        this.rxStompService.activate();
        // other things to do 
    }
}
```

The underlying `onConnect` from `Client` is exposed as an Observable [RxStomp#connected$](https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#connected$). Subscribe to this toexecute code after connection is established:

```typescript
    this.rxStompService.connected$.subscribe(() => {
        // your code
    });
```

**Comment by zymr-keshav** [comment]
Thanks for quick replay, I figure it out how to work and do the same as you mentioned.
now I have done this.

```ts
checkConnection() {
        this.rxStompService.connected$.subscribe((state: RxStompState) => {
            console.log({ state });
            this.connectionStatus = RxStompState[state];
        });
    }
```

but the actual need of this is I want to set the maximum retry of WebSocket or to prevent the reconnection if already connected. How do I archive this?
I have tried with `ReplaySubject(1)` but no hope.

**Comment by kum-deepak** [comment]
You may use https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#connected to check if it is connected.

**Comment by zymr-keshav** [comment]
I know this method but how does this help when page reload/refresh?

**Comment by ibhargav90** [comment]
@kum-deepak  Any update on this documentation.?

**Comment by kum-deepak** [comment]
@ibhargav90 what specifically are you looking for?

**Comment by ibhargav90** [comment]
Looking for this,

> I know this method but how does this help when page reload/refresh? Will you suggest an approach with stackblitz

On page reload, how can i persist connection.

**Comment by kum-deepak** [comment]
It is not possible to persist the connection on a page reload.

**Comment by ibhargav90** [comment]
`		this.numRetries = 3;
        const stompConfig: InjectableRxStompConfig = {
            ...RxStompConfig,
            connectHeaders: this.headers,
            beforeConnect: () => {
            this.connectionSubscription$ = this.rxStompService.connectionState$
				.pipe(filter((state: number) => state === StompState.CLOSED))
				.subscribe(() => {
					console.log('Retrieval count after subscribe', this.numRetries);
					if (this.numRetries <= 0) {
						this.disconnect();
					}
					this.numRetries--;
				});
            }
        };

        this.rxStompService.connected$.pipe(skip(1)).subscribe(() => {
            this.numRetries = this.MAX_RETRIES; // reset the number of tries while connected back
            this.sendMessage(this.command.INCIDENT_LIST);
            this.topicSubscription = this.rxStompService
                .watch(`/topic/${this.uniqueID}`, {
                    ...this.headers,
                    id: `topic_1`
                })
                .pipe(takeUntil(this.ngUnsubscribe))
                .subscribe((message: Message) => {
                    const receivedMessage = JSON.parse(message.body);
                    console.table({ receivedMessage });
                    const isConnected = this.rxStompService.connected();
                    this.service.setConnectionStatus(isConnected);
                    // do task for watching 
                });
        });

        this.uniqueID = this.utils.getUniqueId();
        this.rxStompService.configure(stompConfig);
        this.rxStompService.activate();
        this.isConnectionEstablished = true;`

I have done this as per this discussion, however i can still get multiple subscription for topic.
Do you suggest anything that can be helpful for unsubscribing connectionState$ and  topicSubscription$ ?

The connection is closed after sometime automatically, i want to unsubscribe all the topics and connectedState so we can avoid multiple subscription?

**Comment by kum-deepak** [comment]
Your code has issues and is likely to lead to issues like multiple subscriptions and leaks. Unless your requirements are very specific, please follow the tutorial (https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html) and sample (https://github.com/stomp-js/ng2-stompjs-angular7). These are based on our production applications.

The library itself does not disconnect on its own, there is likely to be some other reason (please keep that discussion in stomp-js/ng2-stompjs#146).

**Comment by mauicoder** [comment]
Hi Deepak,
I'm trying to disable the auto-connection (it is performed from angular-DI). As written in the title, is there a way to disable the auto-connect ? It would be nice to have a disable auto-connect in the configuration.
I tried to use the beforeConnect in my rx-stomp-config.ts, it is called before connecting, but the configuration is in a separated file where I have no access to the RXStompService instance, so I can't call deactivate().

I tried to use the AfterContentInit at app.component level, but the connection is already open.

What I need to achieve: **do not connect if the client is not completely configured**
So based on an internal check, do not even try to open the websocket.
How can I achieve that?
Thanks for your support!

**Comment by kum-deepak** [comment]
@mauicoder I am making certain assumptions - you are on latest version, you are using something like following in the providers:
```typescript
  providers: [
    {
      provide: InjectableRxStompConfig,
      useValue: myRxStompConfig
    },
    {
      provide: RxStompService,
      useFactory: rxStompServiceFactory,
      deps: [InjectableRxStompConfig]
    }
  ]
```

Change the above to:

```typescript
  providers: [
    RxStompService
  ]
```

With this change, the created instance will not attempt to connect. When you have all required information, call the following to attempt connection:

```typescript
    stompService.configure(config);
    stompService.activate();
```

Basically in this mode, the client remains inactive until `.activate()` is called.

**Comment by mauicoder** [comment]
Thanks for your answer Deepak
Your assumpions are correct and your solution looks great, I'll try it asap.

**Comment by cainaj** [comment]
Hi, I have a question about error handling with this library. I have something like:

startConnetionProcess() {
    this.connecting = true;
    this.pending = true;
    this.authService.getIdToken()
    .pipe(takeUntil(componentDestroyed(this)))
    .subscribe(token => {
      this.token = token;

      const stompConfig = {
        brokerURL: environment.webSocketUrl + '/api/listen',
        connectHeaders: {
          'token': this.token,
          topic: this.topic,
          env: this.env
        },
        debug(str) {
          console.log('STOMP: ' + str);
        }
      };
      this.connect(stompConfig);
    });
  }

where connect() calls a method that executes configure() and activate(). 

My problem comes when there is an error on the server side. If this connection is not established, I can see it if I have the debug option on my stompConfig config; however, inside of debug, i cannot call any functions apparently. I am using Angular 8. How can I handle an error? I haven't seen any references to error handling.

**Comment by kum-deepak** [comment]
@cainaj moved to stomp-js/ng2-stompjs#189.

**Comment by DhanasekaranSelvaraj** [comment]
Hi,

Is there any example to provide stompConfiguration using `useFactory` method since we will fetch domain URL on the fly and it is using `sockJs` protocal. Kindly find my below implementation based on your docs. I have removed **brokerUrl** field from `myRXStomConfig`.

Angular version: 9.1.3

Error: `SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.`

```
import { Client } from '@stomp/stompjs';
import * as SockJS from 'sockjs-client'

const client = new Client();
...

{
      provide: InjectableRxStompConfig,
      useValue: myRxStompConfig,
      multi: true
    },
    {
      provide: InjectableRxStompConfig,
      useFactory: client.webSocketFactory = () => new SockJS("Some https URL"),
      multi: true
    }
```

**Comment by kum-deepak** [comment]
Please refer to the guide https://stomp-js.github.io/guide/ng2-stompjs/ng2-stomp-with-angular7.html and the sample at https://github.com/stomp-js/ng2-stompjs-angular7. I have recently tested - these still work for latest Angular and latest version of this library.

Currently you seem to be using `@stomp/stompjs`, with Angular you may be better off using `@stomp/ng2-stompjs`.

To your main question - please see https://github.com/stomp-js/ng2-stompjs/issues/194#issuecomment-630840872.

**Comment by DhanasekaranSelvaraj** [comment]
Hi Deepak,

Thanks for your quick response. I have already gone through the above mentioned docs and sample but no where i am able to find an actual implementation of `useFactory` to mention `SockJS`  URL (Just some sample snippet of `webSocketFactory` 
available in docs). Additionally for your information i am using `@stomp/ng2-stompjs: 8.0.0`. (Note: `Client` module is auto imported from `@stomp/stompjs`.

Here you can find the full code
```
import {
  InjectableRxStompConfig,
  RxStompService,
  rxStompServiceFactory,
} from '@stomp/ng2-stompjs';
import { myRxStompConfig } from './rx-stomp.config';
import * as SockJS from 'sockjs-client'
import { Client } from '@stomp/stompjs';

const client = new Client();

..................

@NgModule({

providers: [
    {
      provide: InjectableRxStompConfig,
      useValue: myRxStompConfig,
      multi: true
    },
    {
      provide: InjectableRxStompConfig,
      useFactory: initWebSocketFactory,
      multi: true
    },
    {
      provide: RxStompService,
      useFactory: rxStompServiceFactory,
      deps: [InjectableRxStompConfig],
    }
]
})
export class AppModule {}

export function initWebSocketFactory(): Function {
  return client.webSocketFactory = () => new SockJS("https://some-domain.com/BASE_URL/ws");
} 
```

**Comment by kum-deepak** [comment]
Your code should look like following:
```typescript
import {
  InjectableRxStompConfig,
  RxStompService,
  rxStompServiceFactory,
} from '@stomp/ng2-stompjs';
import { myRxStompConfig } from './rx-stomp.config';
import * as SockJS from 'sockjs-client'

..................

@NgModule({

providers: [
     {
      provide: InjectableRxStompConfig,
      useFactory: initConfig,
      multi: true
    },
    {
      provide: RxStompService,
      useFactory: rxStompServiceFactory,
      deps: [InjectableRxStompConfig],
    }
]
})
export class AppModule {}

export function initConfig(): Function {
  const myRxStompConfig: InjectableRxStompConfig = {
    webSocketFactory: () => new SockJS("https://some-domain.com/BASE_URL/ws")
    // other settings
  }; 
  return myRxStompConfig;
} 
```

**Comment by benbabics** [comment]
For the life of me, I cannot get this to work. I am presented with the error:

**Error: Uncaught (in promise): SyntaxError: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
Error: Failed to construct 'WebSocket': The URL 'undefined' is invalid.**

My init function looks like the following:

**app.module**
```
export function websocketInitConfig(): Function {
  const websocketConfig: any = {
    reconnectDelay: 1000,
    webSocketFactory: () => {
      return new SockJS( '/api/websocket' );
    },
    beforeConnect: client => {
      if ( !environment.websocket.isEnabled ) {  // evaluates as true
        client.deactivate();
      }
    },
    debug: msg => {
      console.log( '* debug websocket', msg );
    },
  };

  return websocketConfig;
}


@NgModule({
  imports: [
    CoreModule.forRoot({
      websocketFactory: websocketInitConfig,
    }),
    ...
  ]
  ...
})
export class AppModule { ... }
```

**core.module** (module where RxStomp lives)
```
export type CoreConfiguration = {
  websocketFactory: any;
};

@NgModule()
export class CoreModule {

  static forRoot(config: CoreConfiguration): ModuleWithProviders<CoreModule> {
    return {
      ngModule: CoreModule,
      providers: [
        {
          provide:    InjectableRxStompConfig,
          useFactory: config.websocketFactory,
          multi:      true,
        },
        {
          provide:    RxStompService,
          useFactory: rxStompServiceFactory,
          deps:       [ InjectableRxStompConfig ],
        },
      ]
    };
  }
}
```

**Comment by kum-deepak** [comment]
Please attach your debug messages.

**Comment by benbabics** [comment]
Below is the single debug message:
```
* debug websocket  isConnected false

Error: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
    at O._createWebSocket (main.082efa5588db27a43ff1.js:1)
    at O.<anonymous> (main.082efa5588db27a43ff1.js:1)
    at Generator.next (<anonymous>)
    at a (main.082efa5588db27a43ff1.js:1)
    at t.invoke (zone.js:391)
    at Object.onInvoke (main.082efa5588db27a43ff1.js:1)
    at t.invoke (zone.js:390)
    at e.run (zone.js:150)
    at zone.js:889
    at t.invokeTask (zone.js:423)
    at M (zone.js:831)
    at zone.js:741
    at a (main.082efa5588db27a43ff1.js:1)
    at t.invoke (zone.js:391)
    at Object.onInvoke (main.082efa5588db27a43ff1.js:1)
    at t.invoke (zone.js:390)
    at e.run (zone.js:150)
    at zone.js:889
    at t.invokeTask (zone.js:423)
    at Object.onInvokeTask (main.082efa5588db27a43ff1.js:1)
```


Turns out that when I remove `multi: true`, it works.

**Comment by kum-deepak** [comment]
I do not understand the use of `multi` in Angular well. I have used it only with built-in tokens like `APP_INITIALIZER`.

I am closing the issue for now. If you are still facing the issue, please open a new ticket.
