### ISSUE TITLE
How to prevent websocket reconnection on Page reload/refresh 

### ISSUE THREAD

**Issue by zymr-keshav** [stomp-js/ng2-stompjs#123]
I have successfully connected WebSocket on login using auth token but issue is whenever I reload or refresh the page, all connected reset and connected again.

Is there any way we can check before reconnection whether a connection exists or not? and also can we limit the reconnection limit in this latest RxStomp library. earlier I was able to set MAX to retry  [given here](https://github.com/stomp-js/ng6-stompjs-demo/commit/18855b78584955b3e947157e4d63e462c98935d0) but now how to do this?

**Comment by kum-deepak** [comment]
You can still use the same scheme. Please https://stomp-js.github.io/guide/ng2-stompjs/2018/11/05/migrate-ng2-stompjs-v7.html

It has a list of call replacements.

**Comment by zymr-keshav** [comment]
Thank you for the link but what is the replacement of `connectObservable`?
in Short, I want to know how do I acknowledge that connection has been established and now need to perform some action

**Comment by zymr-keshav** [comment]
okay so this is way in latest version
```ts
 this.rxStompService.connected$.subscribe(() => {
            this.numRetries = this.MAX_RETRIES;
        });
```
