### ISSUE TITLE
StompService connectionState$ never returns state CONNECTED

### ISSUE THREAD

**Issue by FuKe** [stomp-js/ng2-stompjs#124]
Version of ng2-stompjs used: 7.0.1

In the documentation (https://stomp-js.github.io/ng2-stompjs/index.html), it is stated that "stompService.state is a BehaviorSubject which maintains and switches its value as per the underlying Stomp Connection status." and that it can have the following values: CLOSED, TRYING, CONNECTED and DISCONNECTING.

When subscribing to this BehaviorSubject, the states "CLOSED" and "TRYING" is returned in that exact order, but state "CONNECTED" is never returned.

The following codeblock generates the following output:
CLOSED
TRYING
Connected

```TypeScript
this.stompService.connectionState$.map((state: number) => StompState[state]).subscribe((status: string) => {
            console.log(status);
            if(status != "CLOSED" && this.stompService.connected()) {
                 console.log("Connected");
            }
        })
```

So it seems like status TRYING is actually being returned when the service is connected?

**Comment by kum-deepak** [comment]
The documentation for v7 is at following locations:

https://stomp-js.github.io/api-docs/latest/injectables/RxStompService.html
https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#connectionState$

State is the following Enum in v7:

https://stomp-js.github.io/api-docs/latest/miscellaneous/enumerations.html#RxStompState

Please see the above resolves your issue.

Just today I have been working on a sample to watch stomp status. Please check https://github.com/stomp-js/ng2-stompjs-angular7

See the status component:
https://github.com/stomp-js/ng2-stompjs-angular7/tree/master/src/app/status

**Comment by FuKe** [comment]
@kum-deepak thank you very much, I wasn't aware that I was looking at an old version of the documentation. Using RxStompState instead of StompState solved the problem.
