### ISSUE TITLE
checking whether the messages is coming consistently or not.

### ISSUE THREAD

**Issue by yash27** [stomp-js/ng2-stompjs#128]
In my application, I am subscribing to broker using web socket and also getting the messages. I have followed the same example provided in your documentation. I just want to know that is there any way to check whether we are getting messages from end-point consistently? In my case, I need to subscribe to an endpoint and check whether I have received any messages for some interval lets say 1 minute. If I haven't received any message from endpoint then it should show some message or alert. We can do the same using `setInterval` or `setTimeout` . Just want to know is there any way to do the same in `ng2-stompjs` .

**Comment by kum-deepak** [comment]
Feel free to use whatever suits your logic - no particular logic available in this library. In certain specific cases RxJS operators might help as well.
