### ISSUE TITLE
proxy websocket to backend

### ISSUE THREAD

**Issue by gxg10** [stomp-js/ng2-stompjs#129]
Hello. How can i proxy my websocket connection ? 
Using angular guidelines i created proxy.json and added 
{
    "/api": {
        "target": "http://localhost:8080",
        "secure": false,
        "ws": true
    }
}
All my urls in my angular app to my spring backend were converted to this /api.
I would like to do the same with websocket. 
In my myRxStompConfig constant i have brokerURL = ws://localhost:8080/api/socket
My problem is that i am currently serving the angular app to other PC in the network and my trick for the http url works, the only one that doesn't work is the websocket connection. 

Only the PC that runs angular and spring backend can connect to the websocket.

All help is much appreciated.

Kind Regards,

**Comment by gxg10** [comment]
Hello. I have the same error, in chrome console "websocket connection to "ws://localhost:4200/api/socket failed. error in connection establishmement: net:: ERR_CONNECTION_REFUSED".
I must explain my setup. Currently my angular app must run only on local area network so on one PC of the network i am running ng serve --host 0.0.0.0 and the spring app. On the PC that runs the 2 services, http requests and websocket are ok. On any other pc, only the http requests are ok.

**Comment by kum-deepak** [comment]
I think I understand the issue. Please create a function as below:

```typescript
const prepareBrokerURL = (path: string): string => {
  // Create a relative http(s) URL relative to current page
  const url = new URL(path, window.location.href);
  // Convert protocol http -> ws and https -> wss
  url.protocol = url.protocol.replace('http', 'ws');

  return url.href;
};
```

Use `brokerURL = prepareBrokerURL('/api/socket')`.

Basically the WebSocket URL will need to refer to the system that runs your Angular application. The above code picks the http address of the Angular Application and create ws URL using it.

Let me know if it resolves the issue.

**Comment by gxg10** [comment]
It works, i no longer receive errors. Thank you ! The issue can be closed!
