### ISSUE TITLE
Creating two new websocket instead of one.

### ISSUE THREAD

**Issue by ajayshah1992** [stomp-js/ng2-stompjs#136]
import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';
import SockJS from 'sockjs-client';

export function socketProvider() {
  return new SockJS('http://localhost:9001/mvp/stomp/?access_token=tupbtgjtrgm2svp679sr3lo471qt2spv');
}

export const myRxStompConfig: InjectableRxStompConfig = {
  // Which server?
  brokerURL: socketProvider,
 /* webSocketFactory: () => {
    return new SockJS('http://localhost:9001/mvp/stomp/?access_token=tupbtgjtrgm2svp679sr3lo471qt2spv');
  },*/
  connectHeaders: {
    login: 'guest',
    passcode: 'guest'
  },
  heartbeatIncoming: 0, // Typical value 0 - disabled
  heartbeatOutgoing: 20000, // Typical value 20000 - every 20 seconds
  reconnectDelay: 20000,
  debug: (msg: string): void => {
    console.log(new Date(), msg);
  }
};

**Comment by kum-deepak** [comment]
Your question is not clear. Please explain clearly.

**Comment by kum-deepak** [comment]
This ticket will be closed unless more information is provided.
