### ISSUE TITLE
Additional states for better connection control

### ISSUE THREAD

**Issue by snqlby** [stomp-js/ng2-stompjs#141]
It is necessary to know the current connection state. There is no way, except stompClient.active() to know either the current connection was closed manually or scheduled. I suggest to extend states to keep compatibility:
```
export enum StompState {
  ACTIVATED,
  TRYING,
  CONNECTED,
  DISCONNECTING,
  CLOSED,
  DEACTIVATED
}
```
Emitted CLOSED and lack of DEACTIVATED next will mean the connection was scheduled

**Comment by kum-deepak** [comment]
The underlying `Client` instance exposes a property `active` status. See: https://stomp-js.github.io/api-docs/latest/classes/Client.html#active

Till this property is exposed directly, you can use it through https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#stompClient

```typescript
ng2stompClient.stompClient.active
```

**Comment by snqlby** [comment]
@kum-deepak 
How correct is it to call a low-level client directly in terms of design for reactive application?

**Comment by kum-deepak** [comment]
It is possible to inherit these classes and extend functionality. Any API documented in https://stomp-js.github.io/api-docs/latest/ can safely be used (all internal APIs are exluded from the documentation).
