### ISSUE TITLE
Lots of /ws/info?=*** with 200 

### ISSUE THREAD

**Issue by Melissa828** [stomp-js/ng2-stompjs#142]
I am using angular 5 with stompJS 4.0.8 to achieve websocket, apache proxy connection.

"@stomp/ng2-stompjs: "^0.6.3", 
@stomp/stompjs@4.0.8

I am using apache to proxy websocket, I got lots for ws connections in apache access log with three patterns. 
GET /ws/info?t=1554908695963
GET /ws/845/abc/websocket
GET /ws/209/edf/eventsource

**I got issues that lots of /ws/info?t=*** from one IP in application log, please refer to the log captured below.** 
9.85.171.132 - - [14/Apr/2019:02:58:58 +0000] "GET /ws/info?t=1555210734946 HTTP/1.1" 200 76 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735801 HTTP/1.1" 200 78 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735804 HTTP/1.1" 200 78 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735809 HTTP/1.1" 200 79 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735813 HTTP/1.1" 200 77 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735886 HTTP/1.1" 200 78 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735890 HTTP/1.1" 200 77 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735894 HTTP/1.1" 200 79 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735897 HTTP/1.1" 200 79 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
9.85.171.132 - - [14/Apr/2019:02:58:59 +0000] "GET /ws/info?t=1555210735910 HTTP/1.1" 200 78 "https://test***.com/" (https://test***.com/')  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"

Can you please advise what is GET /ws/209/edf/eventsource used for? when it will happen?

        const stompConfig: StompConfig = {
            // Which server?
            url: socketProvider,

            headers: {
                userId: userId,
                xtoken: token
            },

            heartbeat_in: 0, // Typical value 0 - disabled
            heartbeat_out: 20000, // Typical value 20000 - every 20 seconds
            reconnect_delay: -1,
        };

**Comment by kum-deepak** [comment]
Are you using SockJS or WebSocket?

**Comment by Melissa828** [comment]
Sorry for confusion...by checking the code, I think I am using SockJS

import * as SockJS from 'sockjs-client';
import {environment} from "../../environments/environment";

export function socketProvider() {

    return new SockJS("https://test***.com");
}

initStompService(userId, token) {


        const stompConfig: StompConfig = {
            // Which server?
            url: socketProvider,

            headers: {
                userId: userId,
                xtoken: token
            },

            heartbeat_in: 10000, // Typical value 0 - disabled
            heartbeat_out: 20000, // Typical value 20000 - every 20 seconds
            reconnect_delay: 20000,

            debug: environment.wsDebug
        };

        this.userStompService.config = stompConfig;
        this.userStompService.initAndConnect();

        // this.setTimoutSubscribe();
        // console.log(222);
        // console.log(this.userStompService.connected());
        this.userStompService.state.subscribe((data) => {
            console.log('---stomp state change ---');
            const now = new Date();
            const hour = now.getHours();
            const minute = now.getMinutes();
            const second = now.getSeconds();
            console.log(hour + ':' + minute + ':' + second);
            console.log(data);
            console.log('---stomp state change end---');
        });

Please allow me consolidate my issue
1. Why the response is 200, I still got lots of /ws/info?=t***
2. What is /ws/209/edf/eventsource used for? I got more than 100 records in log...
3. Network outage or server restart, even I set reconnect, my websocket connection is not reconnected.

**Comment by kum-deepak** [comment]
SockJS is not WebSocket - it is an emulation. Please read first few sections of https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/09/10/using-stomp-with-sockjs.html 

Auto reconnect fails to work with SockJS - depends on which underlying protocol was in use.

During handshake, SockJS tries different underlying transports - WebSockets being one of those. The Apache log entries seems to relate to those alternate transports. Read more at https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https

In addition, it is not straight forward to proxy WebSockets through Apache.

It seems that you might be working on code that is bit old and may not be entirely written by you. I will suggest the following (not all may be possible in your project):

- Switch to using WebSockets directly (i.e. remove SockJS)
- First test without proxy in between.
- Subsequently add the proxy.
- If you can - Nginx allows easy and performant proxying of WebSockets.
