### ISSUE TITLE
SPRING BOOT SEND JWT TOKEN

### ISSUE THREAD

**Issue by jeremysangroni** [stomp-js/ng2-stompjs#143]
Help !!, I need send JWT TOKEN to websocket in Spring Boot. 

I'm trying to send it as headers in the configuration but it does not work for me, it ends up giving me the following error.

WebSocket connection to 'ws://180.183.84.202:7072/socket' failed: HTTP Authentication failed; no valid credentials available

**Comment by kum-deepak** [comment]
Please check https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#websocket-stomp-authentication-token-based
