### ISSUE TITLE
After multiple subscription , unable to receive messages 

### ISSUE THREAD

**Issue by mWaqasahm3d** [stomp-js/ng2-stompjs#144]
```ts
ngOnInit() {
   .watch('/topic/orders:' + this.user.companyUid)
.subscribe((message: Message) => {
// my business logic
    });
  }
```

I receive messages , suddenly no messages were receiving. if i refresh my page , it again start receiving messages. :( don't now why its happening

**Comment by kum-deepak** [comment]
Please enable debug and attach console output.
