### ISSUE TITLE
Unable to install 7.2.0 using npm

### ISSUE THREAD

**Issue by code247** [stomp-js/ng2-stompjs#145]
I'm trying to install the 7.2.0 version using

`npm i --save @stomp/ng2-stompjs`

but I keep getting 404 for the rxStomp dependency.

`npm ERR! 404 Not Found: @stomp/rx-stomp@^0.3.0 >=0.3.0`

Is this an issue on npm/rx-stomp side?

**Comment by kum-deepak** [comment]
Just now tried running `npm i --save @stomp/ng2-stompjs` on a fresh project and it installed `@stomp/ng2-stompjs@7.2.0`, `@stomp/rx-stomp@0.3.0` and `@stomp/stompjs@5.3.0`. Please check again.

Sometimes there may be temporary failures at npm or some proxy might be misbehaving.

**Comment by policz** [comment]
Hello @kum-deepak 

Still the issue is reproducible for me:

After running npm install, i'm able to see the below issue:

npm ERR! code E404
npm ERR! 404 Not Found: @stomp/rx-stomp@^0.3.0 >=0.3.0

In my package.json file , i 'm using
"@stomp/ng2-stompjs": "7.2.0"

**Comment by kum-deepak** [comment]
Tested using a fresh project. It seems to be working.

I checked https://www.npmjs.com/package/@stomp/rx-stomp - the latest is 0.3.3. It may have one of the following issues:

- Temporary issue at npm.
- Issue with local cache.
- Any proxy misbehaving.

**Comment by policz** [comment]
Actually in my local everything works well as you.

But in Continues Integaration like Jenkins the issue is continuously reproducible
