### ISSUE TITLE
delay in connection close

### ISSUE THREAD

**Issue by deli6z** [stomp-js/ng2-stompjs#149]
Hi. First of all thank you for this library.
We have an issue with the scenario when broker is closing the connection but the client is slow to detect that and therefore we are losing some important updates over WS since we think it is still connected. Every time it is a random period of time which varies from 2 to 5+ minutes.
Client relies on StompStatus and once CLOSE is detected goes to REST polling.
Any idea whether there could be something with the sockjs code or this is likely some network interruptions? This happens randomly few times a week.

Thanks.

**Comment by kum-deepak** [comment]
Currently the client relies on [onclose](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onclose) of the underlying WebSocket.

I can suggest the following to reduce the delay:

- Switch to WebSocket (i.e., do not use SockJS). SockJS may pick up one of many supported [transports](https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https), some of which may add significant delay while firing [onclose](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onclose).
- There is concept of Heart Beats (https://stomp-js.github.io/guide/stompjs/2018/06/28/using-stompjs-v5.html#heart-beating). If your broker supports it, you can use it. Most brokers will allow it to be set as low as 1000ms. It will imply a maximum delay in connection closure to be about 2000ms.

**Comment by deli6z** [comment]
@kum-deepak when you say do not use SockJS what you mean by that? I have the understanding that if browser supports WebSockets then even if client initialized using SockJS it will use WebSockets.
This is what happening for us - we use WebSocket transport however still encounter this delay issue.
Will connection be closed if heartbeat is missed? Only one or more should be missed before it will be closed? Heartbeat is essentially the same as pub/sub communication right?

**Comment by kum-deepak** [comment]
SockJS adds a compatibility layer on top of WebSockets; which introduces few limitations/quirks. Based on error reports from users, I have compiled a document, please see https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/09/10/using-stomp-with-sockjs.html. In summary, SockJS in not same as WebSocket.

Heart Beats are special mechanism defined by STOMP specification (https://stomp.github.io/stomp-specification-1.2.html#Heart-beating). When the broker supports it, if the client does not receive a heart beat as anticipated, the connection will be terminated. Internally Heart Beats are just one byte packets.

**Comment by deli6z** [comment]
Thanks for the info, closing the issue
