### ISSUE TITLE
[Suggestion] Stomp service should not call try_connect in constructor

### ISSUE THREAD

**Issue by Mourdraug** [stomp-js/ng2-stompjs#15]
I'd suggest moving out try_connect() call from service constructor, and leaving method public. Executing any code, that isn't constructing object, inside constructor is considered a bad practice, and forces developers to implement some wierd walkarounds.

Consider situation when your websocket server implements csrf token protection(Default springboot security settings for example), and to connect you need to retrive csrf token through http to include it in stomp header. 

You need to delay try_connect() until you get and set that stomp header, but StompService calls it automatically on constructor. 
So there we need first walkaround, you extend StompService, and override try_connect() to call super.try_connect()  when you get http response. 

But! You can't just inject Http through constructor, or use setters because super constructor always have to be first statement. And so you need another walkaround. (I extended StompConfig and passed Http through it, and can't really think of any cleaner solution)

**Comment by kum-deepak** [comment]
First of all, a mode can be added where the try_connect is not called from the constructor. It can be controlled by a flag.

A longer answer to why it was not already done so:

It is assumed that many of the applications will use Angular's dependencies injection. In that case when another service or component receives it as a dependency it should be ready to use. For example in few of the applications we use the service from more than one components/services. In this case it gives a clean solution.

In my opinion, if you need application logic for initialization this service, you would not be able to use Angular's dependency injection mechanism.

In that case functions (possible exported) can be written that will create/initialize the service.

**Comment by kum-deepak** [comment]
If you want I can create a branch with alternate way to initialize the service, that will have a call to initialize the service (this will take the config). See, if that version gives you a better code structure.

Alternatively, create a minimal server (that I can clone and run, considering I have not programmed in Java since 2006) and Angular code (may be 2 different projects) and share it and we can collectively try to come up with a neat way to initialize the service.

**Comment by Mourdraug** [comment]
That's pretty much what I thought was the reason for this and it's legit reason imo, but it's still quite inconvinient in particular cases. Flag in config would be good quick fix, but wouldn't be very flexible. I feel that most elegant solution, according to SoC principle, would be to separate logic code that can be used standalone from simple Injectable service. So that one can, instead of using built in service, write his own implementation. I'll upload simple server and app I wrote for sake of demonstration to my github in the moment.

**Comment by kum-deepak** [comment]
Thanks, I will have a look at it this weekend.

**Comment by kum-deepak** [comment]
Refactored, and made changes, please see my comments in the pull request.

**Comment by kum-deepak** [comment]
Can I close the issue now?

I will leave #13 open to finish example/documentation.

**Comment by Mourdraug** [comment]
Yes, feel free to close it. Thank you for assistance.
