### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by jstolz** [stomp-js/ng2-stompjs#150]
Hi,
I tried your sample, installation works fine but during execution I receive the error.
**failed: Error during WebSocket handshake: 'Sec-WebSocket-Protocol' header must not appear more than once in a response.**

In the file src\app\my-rx-stomp.config.ts I changed brokerURL to 'wss://diligent-elk.rmq.cloudamqp.com/ws/mqtt' and in the connectHeaders the user and the password.

Any hint for me why a header is duplicated?

Regards
Jürgen

**Comment by kum-deepak** [comment]
You might get this error if the endpoint address is incorrect. Please check the documentation of your broker and verify.

At the least try wss://diligent-elk.rmq.cloudamqp.com/ws/'

**Comment by jstolz** [comment]
I use this endpoint with another library, so the endpoint is OK, username and password too.

The test with your recommended url´s failed with the same error
//brokerURL: 'wss://diligent-elk.rmq.cloudamqp.com/ws/',
//brokerURL: 'wss://diligent-elk.rmq.cloudamqp.com/ws',

This connect test´s failed with "Unexpected response code"
//brokerURL: 'wss://diligent-elk.rmq.cloudamqp.com/',
brokerURL: 'wss://diligent-elk.rmq.cloudamqp.com',
the error => stomp.umd.js:420 WebSocket connection to 'wss://diligent-elk.rmq.cloudamqp.com/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by kum-deepak** [comment]
Please enable debug and attach the console output.

**Comment by jstolz** [comment]
Hi,
I added an excerpt of the console log.
Configuration of the file src\app\my-rx-stomp.config.ts
  debug: (msg: string): void => {
    console.log(`Stomp DebugMsg: ${new Date()}, Msg:${msg}`);
  }

Maybe I can get a test account for our system, would that help?

[STOMP_Debug.log](https://github.com/stomp-js/ng2-stompjs/files/3222068/STOMP_Debug.log)

**Comment by kum-deepak** [comment]
Please send the test account to deepak@kreatio.com

**Comment by jstolz** [comment]
I ordered a test account. Because of a bank holiday in Germany I will receive the credentials next Monday

**Comment by kum-deepak** [comment]
I just signed up with CloudAMQP with a free account. Free accounts do not support web stomp (https://www.cloudamqp.com/docs/web_stomp.html).

Meanwhile, please check if your instance has web_stomp plugin enabled.

**Comment by jstolz** [comment]
I'll have that checked out and keep you informed

**Comment by kum-deepak** [comment]
Just checking, can this issue be closed?

**Comment by jstolz** [comment]
Unfortunately I will not come to test before July, so I close this issue. 
Thx for your support
Jürgen
