### ISSUE TITLE
Manual Reconnect

### ISSUE THREAD

**Issue by deli6z** [stomp-js/ng2-stompjs#151]
Hi. We implemented a manual heartbeat b/c our broker does not support stomp heartbeat version. Based on that we manually disconnect and then try to reconnect again. That does not work consistently creating some duplicate WebSocket connections which can be seen in network tab on Chrome. The way we try to do it:
we call stompService.disconnect() then we rely on stompService.connected() status to try to connect again when status is closed using stompService.initAndConnect() method.
Sometimes it is getting into the situation when it creates multiple (2-5+) connections and things get weird. Anything we are doing wrong? How would you suggest to handle the reconnect from the client side when client initiates the disconnect ?

Thanks a lot!

**Comment by deli6z** [comment]
Version on stompjs we use 
"@stomp/ng2-stompjs": "^0.6.4"

**Comment by kum-deepak** [comment]
This version of ng2-stompjs did have issues on reliably disconnecting (the problem you have reported). Fixing these reliably led to significant refactor of this library and the underlying stompjs libraries.

If you do not have strong reasons, please upgrade to latest version. If you can't upgrade then disable auto reconnect, that would reduce but not eliminate the issue you are facing.

**Comment by deli6z** [comment]
Yeah autoreconnect already disabled via setting the reconnect config to 0. Yeah I was thinking about upgrading but that will take some time. Thanks for the quick reply. Please keep this issue open for now.

**Comment by deli6z** [comment]
Hi @kum-deepak. We upgraded the client to the latest version. One question - is sockjs not supported now which means client has to directly connect to ws protocol instead of http?
Thanks

**Comment by kum-deepak** [comment]
SockJS is still supported. However, you may face issues around reconnecting. My personal suggestion will be to use WebSocket directly if you can and fallback only when needed. Please see: https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/09/10/using-stomp-with-sockjs.html

**Comment by deli6z** [comment]
Ok got. We use spring stomp and are having issues changing it to directly work with ws.
Looks like it should be enough to not call .withSockJS on StompEndpointRegistry but it still does not connect.

**Comment by kum-deepak** [comment]
Just checking, can this issue be closed?

**Comment by deli6z** [comment]
Yes, thanks
