### ISSUE TITLE
Production error only : Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by anakin59490** [stomp-js/ng2-stompjs#161]
Hi,
I have defined module that uses ng-stomp and Angular7.
It works nice except when I build the app and deploy it in Tomcat :

![nocomment](https://user-images.githubusercontent.com/16132965/61190960-adaaa580-a6a4-11e9-9408-dd133c5fe875.jpg)

The problem is that the code in production is minified...

![PUoA6](https://user-images.githubusercontent.com/16132965/61190973-ecd8f680-a6a4-11e9-8300-1e7eda4dba5f.jpg)

but i know it happens when the module is loaded so I have comment and uncomment parts of code in order to locate the error : and it come from providers part :

Here is module :

    `import {NgModule} from '@angular/core';
    import {MaterialModule} from '../app.module';
    import {CommonModule} from '@angular/common';
    import {FormsModule, ReactiveFormsModule} from '@angular/forms';
    import {DataTablesModule} from 'angular-datatables';
    import {RouterModule} from '@angular/router';
    import {CommunicationRoutes} from './communication.routing';
    import {AlertesComponent} from './alertes/alertes.component';
    import {MediasComponent} from './medias/medias.component';
    import {ModalMediaComponent} from './medias/modal.media.component';
    import { ImageViewerModule } from 'ng2-image-viewer';
    import {WebsocketComponent} from './chat/websocket.component';
    import { InjectableRxStompConfig, RxStompService, rxStompServiceFactory } from '@stomp/ng2-stompjs';
    import {myRxStompConfig} from './chat/rx-stomp-config';
    import {NotesComponent} from './notes/notes.component';

    @NgModule({
       imports: [
          CommonModule,
          RouterModule.forChild(CommunicationRoutes),
          FormsModule,
          DataTablesModule,
          MaterialModule,
          ReactiveFormsModule,
          ImageViewerModule
      ],
    declarations: [
        AlertesComponent,
        MediasComponent,
        NotesComponent,
        WebsocketComponent,
        ModalMediaComponent
    ],
    entryComponents: [
        ModalMediaComponent
    ],
    providers: [
        {
            provide: InjectableRxStompConfig,
            useValue: myRxStompConfig
        },
        {
            provide: RxStompService,
            useFactory: rxStompServiceFactory,
            deps: [InjectableRxStompConfig]
        }
    ]
    })
     export class CommunicationModule {}`

When I comment providers part, it works

I have make a try by updating global in index.html :
    `
    <head>
        <base href='/'>

        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png" />
        <link rel="icon" type="image/png" href="./assets/img/favicon.png" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
         <title>MyApp</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />
         <script type="application/javascript"> var global = window; </script>
     </head>
`

but nothing changes.... How can I solve this production error ?

Thank's in advance

**Comment by kum-deepak** [comment]
Same as https://github.com/stomp-js/ng2-stompjs-angular7/issues/15, closing here.
