### ISSUE TITLE
Delay in detecting disconnections on Chrome/Windows

### ISSUE THREAD

**Issue by georgesmhanna** [stomp-js/ng2-stompjs#163]
Hello,

There seems to be a problem on Windows/Chrome whenever Wi-Fi is disconnected from my laptop.

The disconnection is not detected right away, and all messages sent between the time the laptop went offline, and the disconnection is detected, are all lost.

This is not happening on mobile devices running Safari or Chrome (Android & iOS).

I tried to decrease the heartbeat, but did not notice any change.

I am sorry I am new to RabbitMQ, so maybe if I am doing something wrong, it would be great to know what it is.

Thank you!

**Comment by kum-deepak** [comment]
Disconnection detection takes time if SockJS is in use. If that is the case please switch to not use SockJS.

Please attach log output: https://stomp-js.github.io/faqs/2019/05/20/faqs.html#p-how-do-i-enable-logging-p
