### ISSUE TITLE
Support multiple connection to server

### ISSUE THREAD

**Issue by loxon-lab** [stomp-js/ng2-stompjs#168]
We  use microservice pattern, and server has separate Websocket knowledge.

Is there any way, to use multiple connections in one angular client?

Thanks

**Comment by kum-deepak** [comment]
Actually you can create multiple instances of the client without any issue. Are you facing any issues while trying to use multiple client instances.

If you are using SockJS, then you may be constrained by SockJS limitation of only one connection to each distinct server. If you are using native WebSockets there is no such limitation.

Another complexity you may face if you are intending to use Angular's Dependency Injection to inject these classes, let me know if you need assistance in this regard.
