### ISSUE TITLE
Which version is the latest

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#169]
I am confused. in [npmjs ](https://www.npmjs.com/package/@stomp/ng2-stompjs) I see version 7.2.0 was published 8 months ago. 
In master branch I see commits that were done 26 days ago.
Which version is in the master branch now?

**Comment by kum-deepak** [comment]
I have setup dependbot which keeps watching dependencies. These have been set to auto merge if it impacts only dev dependencies. I have also created a GitHub issue template for this repository.

All commits beyond 7.2.0 till date are either dev dependency version change or the issue template related.

So code and distribution files wise it is still same as 7.2.0.

**Comment by pantonis** [comment]
So master branch contains 7.2.0 right? Nothing more

**Comment by kum-deepak** [comment]
Yes

**Comment by pantonis** [comment]
But I see that master had changes merged 26 days ago.
![image](https://user-images.githubusercontent.com/3295086/65040928-3a503900-d95e-11e9-8d6c-1693861c8ae3.png)

And 7.2.0 was released 8 months ago

**Comment by kum-deepak** [comment]
Are you finding any difference?

If in doubt, please checkout the repository and take a diff with 7.2.0 tag.

**Comment by kum-deepak** [comment]
I am closing this, if you find any differences, please open an issue.
