### ISSUE TITLE
How to connect RabbitMQ Server  (x509 certificate) authentication mechanism using Stomp Client

### ISSUE THREAD

**Issue by rkmeesala** [stomp-js/ng2-stompjs#170]
HI ,

I want to connect RabbitMQ Server using certificates (omit the username and Password).
i want use my client is stompjs . please help me how to connect .
my username is my certificate ca name.

references Links :
https://github.com/rabbitmq/rabbitmq-auth-mechanism-ssl
Configuring Client authentication via certificates:
[
 {rabbit,  [ 
    {ssl_listeners, [5671]},
    {auth_mechanisms, ['EXTERNAL', 'PLAIN']},
    {ssl_options, [{cacertfile,"D:/RabbitMQ/certs/MyCA.pem"},
                  {certfile,"D:/RabbitMQ/certs/MyRabbitServer.pem"},
                  {keyfile,"D:/RabbitMQ/certs/MyRabbitServer.key"},
                  {verify,verify_peer},
                  {ssl_cert_login_from, common_name},
                  {fail_if_no_peer_cert,true}]}	

  ]}
].

i was changed my configuration file also .

please guide me ,

Thanks 
RK

**Comment by kum-deepak** [comment]
I am not sure how it will work in its entirety. I can give some suggestions:

- This client connects to RabbitMQ using WebSTOMP (STOMP over WebSockets) .
- You will need to figure out if the rabbitmq-auth-mechanism-ssl works for WebSTOMP (https://www.rabbitmq.com/web-stomp.html).
- The browsers have browser specific mechanisms to authenticate using x509 certificates. WebSockets are HTTP(S) internally, so, same mechanisms work.
- You will need to figure out what headers RabbitMQ STOMP plugin will expect in this case and set those.

**Comment by rkmeesala** [comment]
HI Deepak,
Thank you for quick update .
i was enabled my rabbitmq.config file 
 {rabbitmq_web_stomp,
      [{ssl_config, [{port,       15673},
                     {backlog,    1024},
                     {certfile,   "C:/AXIOM/TPI/certificates/Result/146.254.145.225.chained.crt.pem"},
                     {keyfile,    "C:/AXIOM/TPI/certificates/Result/146.254.145.225.chained.keycrt.pem"},
                     {cacertfile, "C:/AXIOM/TPI/certificates/Result/ca_bundle.crt.pem"},
                     %% needed when private key has a passphrase
                     {password,   ""}]},
					 
	    {ssl_cert_login, true}
					 
	  ]
  },
	
thank you .
Rk

**Comment by rkmeesala** [comment]
HI Deepak,
i think it's possibility very high but i don't know to modify rxstompconfig file omit the user name and password . 
1. how to pass certificates in config file .

please guide me .

Thanks ,
RK

**Comment by SimonTate** [comment]
@rkmeesala, did you ever solve this? I'm currently trying to implement a similar client authentication with web-stomp on rabbitmq.

**Comment by rayate2410** [comment]
Was this ever solved? Can see it is closed.. I'm looking for something similar where the angular app needs to connect to RabbitMQ WebSTOMP using x509 certificate authentication. i.e Setting up password-less authentication.
