### ISSUE TITLE
How do I get the connect request return code? Specifically when its 401.

### ISSUE THREAD

**Issue by sswayney** [stomp-js/ng2-stompjs#171]
Hello, I can see in the debug console that my connect request returns a 401. I'd like to forward the user back to our log in server when this happens. However, I can't seem to find a way to intercept the request's response. I subscribed to websocket errors, but that doesn't tell me why the connection failed.

Thank you

**Comment by kum-deepak** [comment]
Please attach the console output and a copy of your configuration.

**Comment by sswayney** [comment]
Hello and thank you for the awesome wrapper,

I found out what I need to do. So this can be closed. But, for those who may have the same question.

_Apparently_, if I reject and return 401 from the server before the socket upgrade, the browser will log the 401 in the console, but due to browser security constraints will not allow us to handle the 401 response in code(from what I have read - sorry I don't have the link, I've been on a wild journey with this one). 

So, now I am letting the connection go through and throw an AccessDeniedException from the server via message security expression handler which sends the stomp error via socket message to the front end. Then, on the front end I subscribe to stompErrors$ and forwarding the user back to our log in page to log in when the error is access is denied. 

So, I hope this helps anyone else who may run into this issue.
