### ISSUE TITLE
Is there a way to get notified if the connection to the broker drops?

### ISSUE THREAD

**Issue by yaskoo** [stomp-js/ng2-stompjs#173]
I need to get notified if the connection drops and when it's reestablished again.
So far I've tried to subscribe to `connectionState$`, `connected$`, `stompErrors$` and `webSocketErrors$` of `RxStompService`, but they either always return true or don't show anything at all.
Also I've tried to pass some callbacks (onConnect, onDisconnect) of the underlying client, but didn't have much luck with that either, thou I was setting them up directly (service.stompClient.onConnect) which might not be very correct, but couldn't find any docs on this.
I also change the heartbeat values to make sure that this isn't the problem, but it was not.

So my question really is what is the correct (if any) way to setup listeners on (re)connect and disconnect events?
Just to clarify I'm interested in the cases when something unforeseen happens (e.g. somebody trips on the ethernet cable) and not manual disconnect.

**Comment by kum-deepak** [comment]
connectionState$ triggers for every state change, you would need to watch for state `CLOSED`. 

```typescript
const disconnected$ = rxStomp.connectionState$.pipe(
      filter((currentState: RxStompState) => {
        return currentState === RxStompState.CLOSED;
      })
    );

disconnected$.subscribe(() => {
     // will be called for every disconnect
});
```

Directly using `rxStomp.stompClient.onConnect` will mess up this client, please avoid.

Please see following guides as well:

- https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html
- https://stomp-js.github.io/guide/ng2-stompjs/rx-stomp/2018/12/18/connection-status-ng2-stompjs.html

**Comment by yaskoo** [comment]
turns out was my fault I wasn't getting notified for the disconnect simply because spring boot's simple broker doesn't have heartbeats enabled by default.
now the events are triggered by the disconnect comes about a minute after the connection was disrupted - can this time be shorted somehow? 
heartbeats are configured to 1000ms for both incoming and outgoing.

**Comment by kum-deepak** [comment]
Are you  using SockJS?

**Comment by yaskoo** [comment]
no, I'm not using SockJS
here's the console output
```
state CONNECTING
state OPEN

Thu Oct 03 2019 16:46:21 GMT+0300 (Eastern European Summer Time) "<<< PONG"
Thu Oct 03 2019 16:46:22 GMT+0300 (Eastern European Summer Time) ">>> PING"
...
Thu Oct 03 2019 16:46:39 GMT+0300 (Eastern European Summer Time) ">>> PING"
Thu Oct 03 2019 16:46:40 GMT+0300 (Eastern European Summer Time) ">>> PING"
Thu Oct 03 2019 16:46:40 GMT+0300 (Eastern European Summer Time) "did not receive server activity for the last 2938ms"
Thu Oct 03 2019 16:46:41 GMT+0300 (Eastern European Summer Time) "did not receive server activity for the last 3937ms"
...
Thu Oct 03 2019 16:47:22 GMT+0300 (Eastern European Summer Time) "did not receive server activity for the last 44937ms"
Thu Oct 03 2019 16:47:23 GMT+0300 (Eastern European Summer Time) "did not receive server activity for the last 45937ms"
﻿

Thu Oct 03 2019 16:53:49 GMT+0300 (Eastern European Summer Time) "Connection closed to ws://..."
state CLOSED
Thu Oct 03 2019 16:53:49 GMT+0300 (Eastern European Summer Time) "STOMP: scheduling reconnection in 500ms"
state CONNECTING
Thu Oct 03 2019 16:53:50 GMT+0300 (Eastern European Summer Time) "Opening Web Socket..."
WebSocket connection to 'ws://...' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE
```

**Comment by kum-deepak** [comment]
Let me check, this is a feature not tested by any of the automated tests. Give me few days.

**Comment by kum-deepak** [comment]
Which browser are you using?

**Comment by yaskoo** [comment]
It's chrome thru electron app.

**Comment by yaskoo** [comment]
so, actually chromium is 69.0.3497.106 and electron - 4.0.5

**Comment by kum-deepak** [comment]
I checked the code. Internally this library uses WebSockets to connect to the server. After putting 'did not receive server activity for the last 2662ms' to log, it issues a `.close` on the underlying WebSocket (https://github.com/stomp-js/stompjs/blob/master/src/stomp-handler.ts#L256). Before trying to open a new connection, it waits for the underlying WebSocket to actually close (indicated by `.onclose` handler, https://github.com/stomp-js/stompjs/blob/master/src/stomp-handler.ts#L143). In this case it seems that the actual closing of the WebSocket takes about a minute.

The WebSocket implementations, for security reasons, restrict access to the underlying TCP socket. There is no way to probe if the underlying TCP connection is broken. So, not sure if we can make the situation better.

**Comment by yaskoo** [comment]
Thank you for looking at this. 
I'll close this, but just a suggestion - maybe it's good to emit some kind of event when the  "did not receive server activity for the last **N**ms" thing happens.

**Comment by jbakoc1** [comment]
We have the exact same problem and I believe it is a common issue. We must inform the user that the connection is lost. It will be nice to raise an event after n time of retries. Otherwise we must monitor the debug msg.

**Comment by kum-deepak** [comment]
Please elaborate on what you are looking for, this issue mention two different things:

- Notification if the broker connection is dropped. See https://github.com/stomp-js/ng2-stompjs/issues/173#issuecomment-537785398
- Delay in notification in a few cases if the connection has dropped. See https://github.com/stomp-js/ng2-stompjs/issues/173#issuecomment-538310161

Please file a new issue with details. Thanks!

**Comment by jbakoc1** [comment]
Sorry for the misunderstanding but I am referring to the https://github.com/stomp-js/ng2-stompjs/issues/173#issuecomment-538310161 as was the last from you.
I believe you can handle it better if you monitor the "did not receive server activity for the last 60661ms" messages.
If you still think it better to open a new issue I will be happy.

**Comment by kum-deepak** [comment]
I have attempted to solve this issue through an alternate approach. I have added an option (in the `develop` branch, not released on NPM yet) of the underlying library https://github.com/stomp-js/stompjs/ by adding a flag `discardWebsocketOnCommFailure` to allow discarding the WebSocket even before it is fully closed, so, reconnects are quicker. I was looking for some beta testers for this feature. Please let me know if you would be interested.

**Comment by jbakoc1** [comment]
I will be more than happy to help. Waiting for the details.

**Comment by kum-deepak** [comment]
I will release a few beta versions in a couple of days.

**Comment by kum-deepak** [comment]
Please see https://github.com/stomp-js/rx-stomp/issues/251 and test it out.
