### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by elion** [stomp-js/ng2-stompjs#175]
Will Angular 9 and ivy be supported?

**Comment by kum-deepak** [comment]
It will be supported. Please try it out, if it does not work, raise a ticket.

**Comment by elion** [comment]
OK. Thank you for the quick reply.

**Comment by Vandereij** [comment]
Has anyone been successful on Angular 9 with Ivy?

**Comment by kum-deepak** [comment]
Please try it out and report your success/failure.
