### ISSUE TITLE
Getting exception while connecting

### ISSUE THREAD

**Issue by sagarwadekar2011** [stomp-js/ng2-stompjs#177]
Hi,
I am getting the following exception while connecting. 
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state

I have used the `connected$` observable and in the subscription, I am sending the initial message. But the subscription callback function gets called more than one time.  here is my code.

this.rxStompService.connected$.subscribe( () => {
if (this.rxStompService.connected()) {
            this.rxStompService.publish({
                destination: `/message/${this.uniqueID}`,
                body: JSON.stringify(message),
                headers: this.headers()
            });
});

The exception is not always.

**Comment by kum-deepak** [comment]
The library internally takes cares of checking if the underlying connection is there, if not, it waits till connection is established and then publishes the message. See: https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#publish

So, you need only the following in your code:

```typescript
            this.rxStompService.publish({
                destination: `/message/${this.uniqueID}`,
                body: JSON.stringify(message),
                headers: this.headers()
            });
```

You code, the way it has written, will send the message every time underlying connection is established. I do not think that is what you had intended.

**Comment by sagarwadekar2011** [comment]
Hello Deepak,

If I simply put the code like yours, out-side any subscription (connected$) it throws the same error. I would like to mention that I am checking the `RxStompService.connected()` value before the publish and it is `true` as expected. But still the same error.

Not getting what is going wrong here..

Regards,
Sagar

**Comment by kum-deepak** [comment]
Enable debug and attach complete log. Which server are you using?

See https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html and sample at https://github.com/stomp-js/ng2-stompjs-angular7 as well.

**Comment by sagarwadekar2011** [comment]
I am using Spring Boot with STOMP for WebSocket on server side.  Please find the attached logs.
[Web-Socket-Logs.log](https://github.com/stomp-js/ng2-stompjs/files/3873256/Web-Socket-Logs.log)

**Comment by kum-deepak** [comment]
You log seems definitely peculiar. The connection seems to have gone away and re-connection happening immediately after.

I will suggest that clone the Angular sample and see if it works. If yes, proceed from there.

For me to assist further, I will need access to minimal server (spring boot) and Angular front-end that demonstrates the issue. You can share these as a GitHub repository.

**Comment by sagarwadekar2011** [comment]
Hello Deepak,
I found that when my code is like below then only the connection lost first time and then it reconnects. 
Here I am using the code from `https://github.com/stomp-js/ng2-stompjs-angular7` repo. 
The only change in the `app.component.ts` file. I have attached the `app.component.ts` and two Java code file. 

Here I have done the configuration in `app.component.ts`. I think it is the main issue.

I have also test the issue with the code in `https://github.com/stomp-js/ng2-stompjs-angular7`, only changing the broker url and topic names. I works fine.

[Websocket Issue.zip](https://github.com/stomp-js/ng2-stompjs/files/3896938/Websocket.Issue.zip)

**Comment by kum-deepak** [comment]
Two issues with your code:

- `activate` is getting called twice (this is the reason that it is getting connected one more time). No need to call it from app.component.ts.
- `watch` is called inside `this.rxStompService.connected$.subscribe`, this will cause watch to be established multiple times. It needs to be outside. `watch`, on its own, will be established again in case of a reconnection.

The code in `app.component.ts` should be similar to following:

```typescript
  initStomp() {
      this.rxStompService.watch('/topic/reply').subscribe( (message: Message) => {
        console.log('Received message', message);
        const bodyMessage = `Message generated at ${new Date}`;
        this.rxStompService.publish({ destination: '/topic/reply', body: bodyMessage});
      });
  }
```

I have copied your code. One caution, I have not checked your Java files, however, the above code might give you an infinite number of messages.

**Comment by sagarwadekar2011** [comment]
Hello Deepak,

Thanks for the information. The issue is because of the `activate()` getting called two times, one by the stomp library and the second time in the code.
