### ISSUE TITLE
Advice: Testing subscriptions in multiple browser tabs / sessions

### ISSUE THREAD

**Issue by JamieKalloe** [stomp-js/ng2-stompjs#179]
Hi there,

I'm looking for some advice / best practises regarding the testing of RxStomp subscriptions using multiple browser sessions.

Right now I'm using the STOMP plugin for RabbitMQ, and I'm using RxStomp for the client side.
Whenever I open a new browser tab (to simulate another subscriber) the subscription id will still be 0.

Example:
`>>> SUBSCRIBE
ack:auto
id:sub-0
destination:event.ronde.1.registered-jury`

This behaviour results in just one subscriber (of sub-0) receiving the message.
What I want to test is simulating multiple subscribers, using multiple browser tabs, so that every tab will be assigned an unique sub-id and that all browser tabs will receive the message.

Some guidance on this problem would be very much appreciated!

Thanks and happy holidays!

Jamie

**Comment by kum-deepak** [comment]
Closed in favor of https://github.com/stomp-js/rx-stomp/issues/166
