### ISSUE TITLE
Stomp client ignores configuration URL

### ISSUE THREAD

**Issue by the-specialist** [stomp-js/ng2-stompjs#18]
In our @angular/cli 1.2.1 project with @stomp/ng2-stompjs 0.4.2 the client ignores the url in StompConfig and connects to the webpack development server instead. Providing an existing SockJS connection doesn't have this issue. I am assuming this would only occur in development.
`url: 'ws://localhost:4200/ws/service'`
-> connects to http://localhost:4200/sockjs-node/info?t=1500962165906
`url: new SockJS('/ws/service')`
-> connects to http://localhost:4200/ws/service/info?t=1500962165906

Thanks for your effort

**Comment by kum-deepak** [comment]
Are you trying to use SockJS? In that case you must pass a function that returns a SockJS object (please see https://github.com/stomp-js/ng2-stompjs/blob/master/SockJS.md). Even though it may seem to work just passing the SockJS object, it will misbehave when it tries to reconnect.

Below is informational:

- Depending on which library you are using at the server side, what you are seeing may actually be expected behavior.
- The behavior does not depend on Development or production environment.
- SockJS and Webscoket provide similar functionality, however, their handshake sequences are quite different. For that reason the server side URL endpoints are also different.

**Comment by the-specialist** [comment]
Thanks very much for the useful information, I've changed my code accordingly.

I only switched to providing the SockJS because otherwise it won't connect to the url i specified as a string.
With the string configuration I am only seeing connections to the webpack development server.

String configuration:
```
http://localhost:4200/sockjs-node/info?t=1500969460062
http://localhost:4200/sockjs-node/681/wn3uuuxu/xhr_streaming?t=1500969460709
```
The first request is always made to the webpack development server. The second connection is established by stompjs.

SockJS provider configuration:
```
http://localhost:4200/ws/service/info?t=1500970399397
http://localhost:4200/sockjs-node/info?t=1500970399399
http://localhost:4200/ws/service/159/wob4xlzv/xhr_streaming?t=1500970405320
http://localhost:4200/ws/service/159/wob4xlzv/xhr_send?t=1500970405535
```

Debugging this.client.ws_fn() in try_connect() with the string configuration yields:
`WebSocket {url: "ws://localhost:4200/ws/service" ...`

But this url is never called. I hope this explains the issue more clearly, the SockJS workaround is fine for me.

**Comment by kum-deepak** [comment]
Great to know that at least it works with SockJS.

Which library you are using at the NodeJS end?

**Comment by the-specialist** [comment]
I've tested the app in Firefox and it calls the correct url, so there must be a bug in Chorme/Chromium. Unfortunately I didn't expect that this could be the source of the error.

**Comment by kum-deepak** [comment]
Would it be possible for you to share a version that reproduces this problem?

**Comment by the-specialist** [comment]
Here's the environment info:

Node: 7.10.0
Chromium: 59.0.3071.109
RabbitMQ: 3.6.6

It could be a general limitation, that there's only one websocket connection allowed to the same port on a server.

Pretty old but similar:
https://stackoverflow.com/questions/12498429/multiple-websockets

**Comment by kum-deepak** [comment]
Are you trying to connect to a RabbitMQ 3.6.6 server?

**Comment by the-specialist** [comment]
We're using RabbitMQ and it requires the SockJS configuration anyway, so I don't really have a choice :). I've also attempted to use the external url instead of the proxied path on localhost, which estabilishes a webscoket connection to the correct url and path.

The problems encountered aren't related to the ng2-stompjs at all.

Thanks for the support and providing the best typescript stomp api available.
