### ISSUE TITLE
Silent unsubscribe from topic

### ISSUE THREAD

**Issue by jbakog** [stomp-js/ng2-stompjs#182]
Hi, I noticed that when I get a message that is not proper json formatted the RxStompService is automatically unsubscribing. Is there any function I can override to notify user that or better stop unsubscribing? 

Thanks

**Comment by kum-deepak** [comment]
I have not checked myself. Please try to use a try/catch around your JSON parsing code. Please let me know if it does not resolve your issue.

**Comment by jbakog** [comment]
I haven't thought of that. It worked like a charm!
