### ISSUE TITLE
How to detect disconnect status when user logout or close tab?

### ISSUE THREAD

**Issue by tamht298** [stomp-js/ng2-stompjs#183]
I want to check user connect and disconnect to my website. I use Spring Boot as a webservice API and Angular as a front-end.

**Comment by kum-deepak** [comment]
Do you want to detect in the back-end (Spring Boot)?

**Comment by tamht298** [comment]
> 
> 
> Do you want to detect in the back-end (Spring Boot)?

I want to display online status for manage user module. But i don't know should I save status column on database?

**Comment by kum-deepak** [comment]
Does `SessionDisconnectEvent`  help you?

https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/websocket.html#websocket-stomp-appplication-context-events

**Comment by tamht298** [comment]
> 
> 
> Does `SessionDisconnectEvent`  help you?
> 
> https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/websocket.html#websocket-stomp-appplication-context-events

So Need I create a column for 'online_status' field in database?

**Comment by kum-deepak** [comment]
Probably you need. It depends on your application logic.
