### ISSUE TITLE
Websocket sessionid connection

### ISSUE THREAD

**Issue by pdaniel-frk** [stomp-js/ng2-stompjs#184]
On my spring boot application i am using the header simpSessionId @Header("simpSessionId") String sessionId to get the socket session id. How can i get this id on the client side without using SockJS. Do you have an example?

Thx.

**Comment by kum-deepak** [comment]
[WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) do not allow access to underlying HTTP headers.

You can, however, access any headers from STOMP communication.

**Comment by pdaniel-frk** [comment]
Do you have an example accessing the session id?

**Comment by kum-deepak** [comment]
No.
