### ISSUE TITLE
Compatibility issues question

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#19]
Hi,

I saw this "Compatibility
There were compatibility issues reported, so this project has now switched to source distribution. In case it does not work for your setup, please raise a ticket."

Can you explain further please?

**Comment by kum-deepak** [comment]
Please see #9 and even I was getting errors while including it is some projects about class mismatches. After switching to source release the issues were resolved. The current NPM package includes the sources only (no compiled JS files).

**Comment by pantonis** [comment]
ok. From which version sources are included?

**Comment by kum-deepak** [comment]
0.3.9 onward.

**Comment by pantonis** [comment]
Thanks Deepak
