### ISSUE TITLE
Anything For React native ?

### ISSUE THREAD

**Issue by Anujmoglix** [stomp-js/ng2-stompjs#190]
Hi I want to use it in my React native App.Please guide me 

Please see FAQs at https://stomp-js.github.io/faqs/2019/05/20/faqs.html before reporting.

**Comment by kum-deepak** [comment]
If you are using RxJS you should try https://github.com/stomp-js/rx-stomp (see: https://stomp-js.github.io/faqs/faqs.html#p-which-one-i-should-use-stompjs-rx-stomp-or-ng2-stompjs-p). Alternatively https://github.com/stomp-js/stompjs will work as well.

ReactNative has a known issue, please see details and workaround at: https://stomp-js.github.io/faqs/faqs.html#p-i-am-using-it-with-react-native-i-have-started-facing-strange-issues-p
