### ISSUE TITLE
set brokerURL through API Call

### ISSUE THREAD

**Issue by MatthiasSomay** [stomp-js/ng2-stompjs#194]
I'm trying to dynamically set the BrokerUrl for my application. The application will be hosted on a Raspberry Pi, so for the client to connect, it needs to set the BrokerURL to its IP, depending on the network. Instead of using a factory like in the tutorial : 

`import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';

export const appRxStompConfig: InjectableRxStompConfig = {

  brokerURL: 'ws://127.0.0.1:8080/stomp/websocket',

  heartbeatIncoming: 0,
  heartbeatOutgoing: 20000,
  reconnectDelay: 5000,

  debug: (msg: string): void => {
    console.log(new Date().toLocaleString('nl'), msg);
  }
}

`

I want to get the host IP from the Spring Boot back-end like this:
`@GetMapping(value = "/api/gethostip")
    public String getHostIpAddress() {
        try {
            InetAddress address = InetAddress.getLocalHost();
            return address.getHostAddress();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
        return null;
    }`

I tried doing it this way, which seemed the easiest to achieve this, creating a class and registering it in app.module:

`import { SettingsService } from './settings/settings.service';
import { OnInit } from '@angular/core';
import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';

export class Stomp {

  public brokerURL = null;
  public heartbeatIncoming: 0; // Typical value 0 - disabled
  public heartbeatOutgoing: 20000; // Typical value 20000 - every 20 seconds
  public reconnectDelay: 5000;

  constructor(private settingsService: SettingsService) {
    this.settingsService.getHostIp().subscribe(ip => this.brokerURL = 'ws://' + ip + ':8080/stomp/websocket');
  }

  debug(msg: string): void {
    console.log(new Date().toLocaleString('nl'), msg);
  }

}
`

app.module:

`providers: [
    ScenesService,
    SettingsService,
    RxStompService,
    {
      provide: InjectableRxStompConfig,
      useClass: Stomp,
      deps: [SettingsService]
    }
]`

**Comment by kum-deepak** [comment]
If I understand correctly you want to set the broker URL before the actual connection is made. There are two methods that I know of:

- You can use [APP_INITIALIZER](https://angular.io/docs/ts/latest/api/core/index/APP_INITIALIZER-let.html). This technique blocks the Angular App initialization till a remote request completes. See an older sample using this technique - https://github.com/stomp-js/ng2-stompjs-demo 
- You can use https://stomp-js.github.io/api-docs/latest/classes/Client.html#beforeConnect callback. This callback can be an async function. The actual connection request is made after the function completes.

Please let me know if the above is useful.

**Comment by MatthiasSomay** [comment]
Hi kum-deepak,

Thank you for the quick answer. I was looking online for implementing the beforeConnect function. I finally came to this:

https://imgur.com/a/GscO4K5 

However there seems to be an issue which I can't seem to resolve:

https://imgur.com/a/LjEQoWL

Is it because the Angular version of stompjs still uses version 0.3.0 of rxStomp?

Am I on the right track?

**Comment by kum-deepak** [comment]
Can you please upgrade to latest versions of `@stomp/ng2-stompjs` and `@stomp/rx-stomp`. Let me know if the issue is still unresolved.

**Comment by kum-deepak** [comment]
It should pick 7.2.0 of `@stomp/ng2-stompjs` and 0.3.5 of `@stomp/rx-stomp`.
