### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by jvvosantos** [stomp-js/ng2-stompjs#197]
Hey, I've come across other issues about the same matter, but all of them were closed due to lack of information and interest. 

I'm using ng2-stompjs version 7.2.0

The config is as follows:

```
import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';

export const myRxStompConfig: InjectableRxStompConfig = {
  // Which server?
  brokerURL: 'ws://18.206.93.33:15674/ws',

  // Headers
  // Typical keys: login, passcode, host
  connectHeaders: {
    login: '--------',
    passcode: '-------'
  },

  // How often to heartbeat?
  // Interval in milliseconds, set to 0 to disable
  heartbeatIncoming: 0, // Typical value 0 - disabled
  heartbeatOutgoing: 20000, // Typical value 20000 - every 20 seconds

  // Wait in milliseconds before attempting auto reconnect
  // Set to 0 to disable
  // Typical value 500 (500 milli seconds)
  reconnectDelay: 200,

  // Will log diagnostics on console
  // It can be quite verbose, not recommended in production
  // Skip this key to stop logging to console
  debug: (msg: string): void => {
    console.log(msg);
    
  }
};
```
My code works as intended on Firefox and I can handle the notifications sent by RabbitMQ fine, but does not work on Chrome and Safari with the following error:

`WebSocket connection to 'ws://18.206.93.33:15674/ws' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

Theres no `rabbitmq.conf` file on my `/etc/rabbitmq` folder, so I'm using the default configuration, I guess.

Enabled plugins are `[rabbitmq_management,rabbitmq_web_stomp,rabbitmq_web_stomp_examples]`

I'll try to provide as much information as needed. 

Thanks a lot

**Comment by kum-deepak** [comment]
What is your RabbitMQ version?

**Comment by kum-deepak** [comment]
I just now tested sample https://github.com/stomp-js/ng2-stompjs-angular7/ (branch angular-7.2). I have RabbitMQ (v 3.7.3) locally installed. With this Chrome is working fine.

Please see if you can test as close to the above setup and we can take it from there.

This error is usually caused when the client sends a sub protocol request and server does not send the corresponding header in the response.

**Comment by jvvosantos** [comment]
Hey, so I've updated my rabbitMQ server version, and it worked fine. Both your example and my application. Thanks a lot!

**Comment by kum-deepak** [comment]
BTW, there was a change in RabbitMQ 3.6.2 to address this. It was because of an ambiguity in the standards - Mozilla and Chrome chose to interpret it differently. Better luck for us that RabbitMQ chose to make an implementation that works for both.
