### ISSUE TITLE
Disconnect and Reconnect with RxStopService

### ISSUE THREAD

**Issue by sir-captainmorgan21** [stomp-js/ng2-stompjs#198]
@kum-deepak I wanted to tag you since you seem fairly active on here. Is there a way to disconnect and reconnect using the RxStompService? We need to be able to do this to start a "new session" with our server.

**Comment by kum-deepak** [comment]
Please call `client.deactivate()`, followed by `client.activate()`. There is a possible race condition (fixing needs change in interface - waiting for the next major release) so, it is advisable to put a slight gap (may be 1000ms using setTimeout) between the two. Before calling activate again, you can alter parameters.

It will try to re-establish all subscriptions and send any outstanding message when new session starts. So, depending on your need, you might prefer to `deactivate` one client and create a new client.

There is a harsh way as well - that involves force closing the underlying WebSocket.

While I do not use any of the above in my application code, all of these techniques are used in test cases.

I may be able to advice further if I understand your underlying reason.
