### ISSUE TITLE
no such file or directory @stomp/ng2-stompjs/index.js

### ISSUE THREAD

**Issue by sjbwylbs** [stomp-js/ng2-stompjs#20]
env: 
ionic 3.6
ionic-cli 3.7
@stomp/ng2-stompjs": "^0.4.2"

log:
Module build failed: Error: ENOENT: no such file or directory, open 'xxxxxx/node_modules/@stomp/ng2-stompjs/index.js'

how to ?

**Comment by kum-deepak** [comment]
This module is distributed as .ts (TypeScript) files. No .js files are generate or bundled.

I have no experience about ionic. At this point https://ionicframework.com is not responding for me. Does ionic use TypeScript files?

**Comment by sjbwylbs** [comment]
yes, ionic 3's project file are all TypeScript file.

**Comment by sjbwylbs** [comment]
At the point i would use the Javascript distributed version?

**Comment by kum-deepak** [comment]
I know you are a very good programmer :)

Can you include https://github.com/stomp-js/ng2-stompjs/tree/master/src/*.ts (just 3 files) into your project, adjust paths and check if it works for you. All functional code is only in these 3 files.

Alternatively, please create a minimal ionic project and I can take a shot.

**Comment by kum-deepak** [comment]
I have not been able to figure out how to do a JavaScript distribution of this library. Yet to find reliable guidelines on Angular module distribution.

Versions 0.3.7 or older were JS distribution. But, that did not work for all setups.

**Comment by sjbwylbs** [comment]
Thank you very much.i am work for create minimal ionic project for test ng2-stomp and sharp you.
for this time,I will include ng2-stompjs first for my proejct.

**Comment by kum-deepak** [comment]
Thanks!

**Comment by sjbwylbs** [comment]
@kum-deepak pls check out this project to valid. https://github.com/sjbwylbs/ionic-ng2-stompjs 

Thanks! :)

**Comment by kum-deepak** [comment]
Thanks, will take a look.

Meanwhile, please try directly including the 3 files from src folder.

**Comment by sjbwylbs** [comment]
Thanks.
and also include the index.ts then fixed the path.
it's cool.

**Comment by vvasiloud** [comment]
I am also experiencing the same issue. Any fix?

**Comment by kum-deepak** [comment]
I tried adding `baseUrl` and `paths` into `tsconfig.json`. Build errors are gone. Please check if it indeed works.

See: https://github.com/sjbwylbs/ionic-ng2-stompjs/pull/1

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "baseUrl": "./src",
    "paths": {
      "@stomp/ng2-stompjs": ["../node_modules/@stomp/ng2-stompjs"]
    }
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by sjbwylbs** [comment]
cool. set the path .let ts compiler the ng2-stompjs first. 
Good job!
