### ISSUE TITLE
Cant do it work with ionic

### ISSUE THREAD

**Issue by CristianRoot** [stomp-js/ng2-stompjs#21]
When I try to use this library in ionic I get this error 

> Module build failed: Error: ENOENT: no such file or directory, open 'C:\workspace\PruebaIonic\node_modules\@stomp\ng2-stompjs\index.js' at Error (native)

In angular 2 this work fine... 

Thanks

**Comment by kum-deepak** [comment]
Please see #20 and check if that helps.

**Comment by CristianRoot** [comment]
It works pretty fine!

Thanks!
