### ISSUE TITLE
Multiple connection

### ISSUE THREAD

**Issue by kelvinsleonardo** [stomp-js/ng2-stompjs#218]
I'm using the follow configuration manual: https://github.com/stomp-js/ng2-stompjs/issues/121#issuecomment-445694772
**Angular: 9.0.7**
**@stomp/ng2-stompjs: 8.0.0**

I am simulating loss of connection with the server. When the library tries to reconnect, some requests / sessions are made successfully. Instead of just one. Check images below

### All status 101 is successful
![detail](https://user-images.githubusercontent.com/7854286/106480341-0eb5ec00-648a-11eb-9473-81b35d35c38b.png)
### First connection successful
![detail2](https://user-images.githubusercontent.com/7854286/106481569-525d2580-648b-11eb-8683-85f0deeebf68.png)
### Second connection successful
![detail3](https://user-images.githubusercontent.com/7854286/106481855-9fd99280-648b-11eb-9667-6c7f89f8eb21.png)

**Comment by kum-deepak** [comment]
The v8 has some additional logic, which may cause this behavior. Please share your configuration and debug output.

**Comment by kelvinsleonardo** [comment]
### Config
     
      export const websocketStompConfig:InjectableRxStompConfig = {
     
        brokerURL: 'ws://url-server/socket',
    
        connectHeaders: {
          Authorization: 'guest',
          passcode: 'guest',
        },
    
        heartbeatIncoming: 0, 
    
        heartbeatOutgoing: 20000,
    
        reconnectDelay: 2000,
      
        debug: (msg: string): void => {
          console.log(new Date(), msg);
        }
    };`

### Init
     private initStomp() {
          const stompConfig: InjectableRxStompConfig = Object.assign({}, websocketStompConfig, {
              connectHeaders: {
                  Authorization: this.webStorage.userAuthorization
              },
              brokerURL: `${Constant.WEBSOCKET}?Authorization=${this.webStorage.userAuthorization}`,
              beforeConnect: () => {
                  // console.log('%c called before connect', 'color: blue');
              }
          });
  
          this.rxStompService.configure(stompConfig);
          this.rxStompService.activate();
      }

### App module
    providers: [RxStompService]

![1](https://user-images.githubusercontent.com/7854286/106601373-5300c500-653a-11eb-9e3b-d85200d2e051.png)
![2](https://user-images.githubusercontent.com/7854286/106601367-52682e80-653a-11eb-9b92-12f443e03dd2.png)
![3](https://user-images.githubusercontent.com/7854286/106601361-51370180-653a-11eb-86c6-5519298a79cd.png)

**Comment by kum-deepak** [comment]
Thanks for the detailed diagnostic report. One new feature was intorduced in v8 of this library - https://stomp-js.github.io/guide/stompjs/rx-stomp/upgrading-to-stompjs-6-rx-stomp-1.html#connectiontimeout (https://stomp-js.github.io/api-docs/latest/classes/Client.html#connectionTimeout). It seems it does not work as intended in every case.

Set it to `0` to disable this feature. Let me know if it resolves the issue.

**Comment by kelvinsleonardo** [comment]
It worked. Thank's

**Comment by kum-deepak** [comment]
Released @stomp/stompjs@6.1.0 and @stomp/rx-stomp@1.0.2. It sets https://stomp-js.github.io/api-docs/latest/classes/Client.html#connectionTimeout to 0 to de-activate this feature.
