### ISSUE TITLE
Is it possible to have multiple configuration?

### ISSUE THREAD

**Issue by offwork** [stomp-js/ng2-stompjs#22]
I am providing the configuration in my project using SockJS. Should this configuration be started in AppModule? Is it possible to use more than one StompConfig in one module?

**Comment by kum-deepak** [comment]
There can be any number of instances of the service be created. It follows the Angular Dependency Injection. Please read https://angular.io/guide/dependency-injection 

Specifics will vary depending on you actual requirements. Let me know more details if you need further assistance.
