### ISSUE TITLE
Problems receiving messages! Angular 9

### ISSUE THREAD

**Issue by JoaoGabrielDePaula** [stomp-js/ng2-stompjs#224]
Good afternoon!

I'm using Angular 9 and sometimes it happens to send a message when using "publish" and not receiving through "watch". I checked and the message arrives at the server and is sent without any error. To get back to work I have to restart my front. This has already happened in the cloud and on my local machine. I haven't found anything to solve my problem so far. Do you know what it can be?

Thank you very much in advance!

**Comment by kum-deepak** [comment]
Please enable debug (see https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html#debug) and check the console output. If that does not help, please attache the debug output for me to check.
