### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by yquintana** [stomp-js/ng2-stompjs#227]
hi, this error was displayed at  in compile time.

ERROR in node_modules/@stomp/rx-stomp/esm6/rx-stomp.d.ts:124:9 - error TS1086: An accessor cannot be declared in an ambient context.  
[ng] 124     get stompClient(): Client;
[ng]             ~~~~~~~~~~~
[ng] node_modules/@stomp/rx-stomp/esm6/rx-stomp.d.ts:193:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 193     get active(): boolean;

**package.json**
        "socket.io-client": "^4.0.1",
        "sockjs-client": "^1.5.1",
        "@stomp/ng2-stompjs": "^8.0.0",
        "@stomp/stompjs": "^6.1.0",
        "@angular/cli": "~8.3.23",

**Comment by kum-deepak** [comment]
I did encounter this issue last year. Unfortunately, I could get information other than that it is caused by a version mismatch of compilers - the one used to compile the library and one used by the user of the library.

Please see https://github.com/stomp-js/rx-stomp/issues/308 for a workaround.

**Comment by kum-deepak** [comment]
It seems typescript dependency had gotten relaxed - maybe by - dependabot. Version 3.9.99 was getting used. As part of release 1.1.2, typescript is contained back to 3.6.x. Hopefully, it should work without the workaround now.

Leaving this issue open for reports of it working/failing.
