### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received 

### ISSUE THREAD

**Issue by trannamit95** [stomp-js/ng2-stompjs#23]
Hi. I'm facing this error when I connect with stomp of rabbitmq.
I have tested in more servers, some working well, some failed. Pls help.

```
VM14753:161 WebSocket connection to 'ws://rabbitmq.xxxx.com:15674/ws' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

ng2-stompjs version:  0.4.2
@angular/: 2.4.0

**Comment by sjmf** [comment]
Post your RabbitMQ config please, e.g `/etc/rabbitmq/rabbitmq.config`. It is very likely to be your server config.

**Comment by trannamit95** [comment]
@sjmf I have 3 file in rabbitmq folder:

rabbitmq.config.bak
```
[
  {rabbit, [
    {tcp_listeners, [{"::",81}]}
  ]}
].
```

enabled_plugins
```
[rabbitmq_management,rabbitmq_stomp,rabbitmq_web_stomp].
```

rabbitmq-env.conf
```
RABBITMQ_NODE_PORT=5672
```

**Comment by sjmf** [comment]
`rabbitmq.config.bak` will not be read, as it is a backup. According to the documentation https://www.rabbitmq.com/web-stomp.html it looks like when no config is specified it will serve from the default of 15674– which your code is hitting, presumably.

The "no response was received" makes me think that your websocket connection is never getting as far as your Rabbit server though. Could you check the port on 15674 to see if it is open?

You could also enable `rabbitmq_web_stomp_examples` in RabbitMQ and see if that example can open a connection to your server.

**Comment by kum-deepak** [comment]
Any further information on this issue?

If none, this issue will be closed.

**Comment by vittal288** [comment]
I am facing the same issue, we are using STOMP websocketing library but getting following error in chrome 
WebSocket connection to 'wss://URL' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in the request: stomp

**Comment by kum-deepak** [comment]
Please send additional details:

- Which server you are using, if RabbitMQ then your rabbitmq.config
- Full console output
- Actual URL that you are using

If you are using RabbitMQ please see commnet https://github.com/stomp-js/ng2-stompjs/issues/23#issuecomment-326818785 above.

**Comment by kum-deepak** [comment]
Closing the issue for lack of interest.
