### ISSUE TITLE
not working publish to send messages

### ISSUE THREAD

**Issue by offwork** [stomp-js/ng2-stompjs#24]
[`this.senderStompService.publish(
            '/app/create/createStockListByWebSocket', 
            JSON.stringify(this.sampleData));`](https://github.com/offwork/websocket-app/blob/f6c4df205be3469439e446406797bccda10a6f3c/src/app/components/socket/sender/socket-sender.component.ts#L89)

in this case continuously "**Will try sending queued messages**" working. Do you have any idea why the stomp server did not write the message?

**Comment by kum-deepak** [comment]
This can happen in several cases. It means that STOMP broker is disconnecting frequently and reconnecting. Please enable debug and check messages in the console.

I will need to see console messages with debug on to help further.

**Comment by offwork** [comment]
Ok, first of all thank you very much for your help 👍  , here are the debug images:
![ekran resmi 2017-09-08 09 34 46 2](https://user-images.githubusercontent.com/10039583/30199712-9799d090-947c-11e7-8da2-9def911cb164.png)
![ekran resmi 2017-09-08 09 36 39 2](https://user-images.githubusercontent.com/10039583/30199714-97a28bae-947c-11e7-8bda-8a33aaa82f83.png)
![ekran resmi 2017-09-08 09 36 56 2](https://user-images.githubusercontent.com/10039583/30199713-979f8332-947c-11e7-8ec1-0a490d00e8c0.png)

**Comment by kum-deepak** [comment]
Not getting much idea, other than the fact that server connection breaks.

Which server are you using?

How many messages are you trying to send (in an hour or minute)?

**Comment by offwork** [comment]
We are use Spring+Tomcat as the server. 
It sends 500 messages in the last attempt and is not specified at any time.

And ng2-stompjs does not automatically reconnect? So, do I need to do something to reconnect?

**Comment by kum-deepak** [comment]
Are you using SockJS?

**Comment by offwork** [comment]
Yes, I use SockJS, [STOMPJS](https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/sockjs.md.html)

do you think this is the problem?

**Comment by kum-deepak** [comment]
Did you configure it as per instruction at https://github.com/stomp-js/ng2-stompjs/blob/master/SockJS.md ?

**Comment by offwork** [comment]
yes, here is my config:

`import { Injectable } from '@angular/core';
import { StompService } from "@stomp/ng2-stompjs";

import * as SockJS from 'sockjs-client';

export function receiverProvider() {
    return new SockJS('http://192.168.0.103:8080/register');
}

@Injectable()
export class ReceiverStompService extends StompService {}

export function receiverStompServiceFactory() {
    return new ReceiverStompService({
        url: receiverProvider,
        headers: {
            login: "guest",
            passcode: "guest"
        },
        heartbeat_in: 0,
        heartbeat_out: 19000,
        reconnect_delay: 5000,
        debug: true
    });
}
`

**Comment by kum-deepak** [comment]
Your Angular side configuration looks correct.

It should have reconnected with this configuration. Other people using Spring with SockJS report that it does reconnect.

It may be worth checking the server logs - generally when the server side throws an error or sends an error down the Scoket, the connection terminates. See if you can find clues at the server end.

One thing that might make debugging easier - though it will not solve your problem - is to switch to using Websocket instead of SockJS.

**Comment by kum-deepak** [comment]
Any further information on this?

**Comment by offwork** [comment]
Yes, it works fine. Please do not laugh, but the problem was due to the incorrect URLs given.

**Comment by kum-deepak** [comment]
That's a relief!

**Comment by offwork** [comment]
exactly
