### ISSUE TITLE
Mock RxStompService connect method

### ISSUE THREAD

**Issue by kravinash13** [stomp-js/ng2-stompjs#245]
How do we mock RxStompService connect method for unit test in Jest.

**Comment by kum-deepak** [comment]
I am not sure if the current version of RxStompService has a connect method. Otherwise mocking should be just like any other object. Please check https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html (RxStompService is an injectable version of RxStomp).

**Comment by kravinash13** [comment]
@kum-deepak Thank you. Was able to write unit test by mocking `RxStompService`.
