### ISSUE TITLE
stomp.startConnect() not pointing to right host

### ISSUE THREAD

**Issue by cepix** [stomp-js/ng2-stompjs#25]
```
   //configuration 
     stomp.configure({
  
       **host:'127.0.0.1:8080',
       debug:true,
       queue:{'init':true}
     });
```
AFter doing stomp.startConnect()  , chrome console shows this error:
` zone.js:2744 GET http://localhost:4200/127.0.0.1:8080/info?t=1505100250266 404 (Not Found)`

![chrome_2017-09-11_00-29-52](https://user-images.githubusercontent.com/12740590/30257417-68de9782-9688-11e7-8dfb-7dba92213a3c.png)

**Comment by kum-deepak** [comment]
Try using 'ws://127.0.0.1:8080' instead of '127.0.0.1:8080' (assuming you are using Websocket).

**Comment by cepix** [comment]
@kum-deepak , SockJS does not allow ws://
```

AppComponent_Host.html:1 ERROR SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed.
    at new SockJS (main.js:73)
```

I found that this problem begins at SockJS library, where the socket constructor is set to a wrong URL.... still trying to find out where this URL is set...
![2017-09-15_13-35-53](https://user-images.githubusercontent.com/12740590/30494243-b7a20f00-9a1d-11e7-8d4e-17c8ea734099.png)

**Comment by kum-deepak** [comment]
Are you sure you are using ng2-stompjs? Your code does not seem to be using ng2-stompjs.

Try using 'http://127.0.0.1:8080' instead of '127.0.0.1:8080'.

**Comment by cepix** [comment]
@kum-deepak that worked!! Amazing...thanks!!
So if I omit the protocol in the hostname  : 

```
stomp.configure({
        host:'127.0.0.1:8080
```
 it points to local angular host 

GET http://localhost:4200/127.0.0.1:8080/api/info?t=1505503829336 404 (Not Found)

...is this a bug ?

**Comment by kum-deepak** [comment]
Not a bug really. That is how HTTP resources are supposed to be addressed - URLs that are not absolute are considered relative and resolved relative to the URL of current page.

In case of Angular apps URL of current page (in development setup) is http://localhost:4200/

I hope the above is helpful.
