### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#261]
Does this library supports Angular 14?

**Comment by kum-deepak** [comment]
You should shift to `rx-stomp`, which has been tested with Angular 13. Please see  https://stomp-js.github.io/guide/rx-stomp/ng2-stompjs/ng2-stompjs-to-rx-stomp.html

**Comment by kum-deepak** [comment]
Also see #251.

**Comment by pantonis** [comment]
Thank you @kum-deepak. Long time to talk. hope you are ok :)
