### ISSUE TITLE
Headers not sent in production environment

### ISSUE THREAD

**Issue by jwz104** [stomp-js/ng2-stompjs#27]
I am simply trying to send an authorization header to the websocket(No SockJS, just websocket) on handshake.

It isn't working when I am building with `--prod`.

The token is only sent without the `--prod`.
Console output:
Normal
![afbeelding](https://user-images.githubusercontent.com/6162114/31358063-6ca38a12-ad44-11e7-8d08-c039934b887c.png)
Production
![afbeelding](https://user-images.githubusercontent.com/6162114/31358106-916cb6fc-ad44-11e7-838c-09e501deec26.png)

The headers just aren't sent when `--prod`.

Why doesn't the build with `--prod` work?
`--aot` also doesn't work.

**Comment by kum-deepak** [comment]
I tested a similar code and it seems to be working. To help narrow down the issue, please log the ws_config to console before passing it to StompService.

**Comment by jwz104** [comment]
My configuration is in the environment files. This is the configuration:
```
export const environment = {
  production: true,
  base_uri: 'http://localhost:8080/',
  ws_config: {
    url: 'ws://localhost:8080/ws',
    headers: {
      Authorization: localStorage.getItem('token'),
    },
    heartbeat_in: 0,
    heartbeat_out: 20000,
    reconnect_delay: 5000,
    debug: true
  },
};
```
This is how I set the config:
```
  providers: [
    {
      provide: StompConfig,
      useValue: environment.ws_config,
    },
  ],
```

When I log in the app.component.ts all the config is right.

But when I log in the constructor of stomp.service.ts this is what I get:
![afbeelding](https://user-images.githubusercontent.com/6162114/31377544-aae0ed56-ada8-11e7-9caa-e284570884b7.png)
The Authorization header is gone...

When running without `--prod` the header is present.

**Comment by jwz104** [comment]
This issue had nothing to do with the package.

It is just that you can't call `localStorage` in the environment files in AOT.

So I was just using the environment files in a wrong way...
