### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by Aslan125** [stomp-js/ng2-stompjs#28]
how to send  authentication header before connect?

**Comment by kum-deepak** [comment]
You can add it to headers filed in the configuration, schematic example:

```
{
    url: 'ws://localhost:8080/ws',
    headers: {
      Authorization: 'XXXXXXXXXXXXXXXXXXXXXX',
    },
    heartbeat_in: 0,
    heartbeat_out: 20000,
    reconnect_delay: 5000,
    debug: true
}
```

**Comment by sandroverna** [comment]
I added the variable:
headers: {
       Authorization: 'XXXXXXXXXXXXXXXXXXXXXX',
     }

but the request headers did not track it:

Accept-Encoding: gzip, deflate, no
Accept-Language: en-us, en; q = 0.8, en-US; q = 0.6, en; q = 0.4
Cache-Control: no-cache
Connection: Upgrade
Cookies: user = delegato1
Host: localhost: 8090
Origin: http: // localhost: 5050
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: B6mduioqg LnbhWEHeLNAw == +
Sec-WebSocket-Protocol: v10.stomp, v11.stomp, v12.stomp
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 61.0.3163.100 Safari / 537.36

**Comment by kum-deepak** [comment]
Sorry, I had misunderstood the question. What I suggested, will add to Stomp connection headers - which happens after WebSocket connection is established.

Unfortunately there is no documented way of setting a generic header on the underlying HTTP request for WebSocket. If your connection needs HTTP basic authentication, you can try ws://user:pass@localhost:8080/ws (https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api).

It may be worth checking the documentation specific to server implementation you are using.

**Comment by sandroverna** [comment]
tanks Deepak Kumar,
I had already read this stackoverflow page but I was hoping that the config headers parameter would refer to headers of the underlying HTTP request for WebSocket call.
instead I suppose it refers to the stomp headers

**Comment by sandroverna** [comment]
does not work :-(

the configuration parameters are now:

{
debug: false,
headers: {},
heartbeat_in: 0,
heartbeat_out: 20000,
reconnect_delay: 5000,
url: "ws: // username: password @ localhost: 8090 / gastbews / 1.0 / alerts / room"
}

but instead of generating one
Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ =
with the encrypted base64 "username: password" string

I have a request url of this type:
ws: // username: password @ localhost: 8090 / gastbews / 1.0 / alerts / room

**Comment by kum-deepak** [comment]
Sorry, don't know any other thing to try.

**Comment by kum-deepak** [comment]
As a last try, see if using SockJS works for you - check the documentation (https://github.com/stomp-js/ng2-stompjs/blob/master/SockJS.md) on how to use. That might work as it uses http:// URL pattern.

**Comment by kum-deepak** [comment]
Did it work for you?

**Comment by MicroLord** [comment]
java springboot , work well !
`@Override
    public void configureClientInboundChannel(ChannelRegistration registration) {
        registration.setInterceptors(new ChannelInterceptorAdapter() {

            @Override
            public Message<?> preSend(Message<?> message, MessageChannel channel) {

                StompHeaderAccessor accessor = MessageHeaderAccessor.getAccessor(message, StompHeaderAccessor.class);

                String token = accessor.getFirstNativeHeader("Authorization");

                accessor.removeNativeHeader("Authorization");

                Authentication authentication = token == null ? null : tokenStore.readAuthentication(token).getUserAuthentication();

                if (StompCommand.CONNECT.equals(accessor.getCommand())) {
                    Authentication user = authentication;
                    SecurityContextHolder.getContext().setAuthentication(user);
                    accessor.setUser(user);
                }

                return message;
            }
        });
    }`

**Comment by kum-deepak** [comment]
Can I close the ticket?
