### ISSUE TITLE
Remove auto connection

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#29]
Can try_connect not called from constructor. 

There are cases that application logic need to finish first before connecting to broker. 
Currently as soon as the instance of the StompService is initialized it is also connected
Need to be able to call connect whenever we want not when instance is created.

**Comment by kum-deepak** [comment]
I can definitely add that as an option. However in most cases there are Angular specific ways to delay initialization - especially when it is during application initialization.

If you are able to provide more details, I might be able to help.

**Comment by pantonis** [comment]
I understand that there other ways but there are scenarioa that is better to call connect. In my case I contact another broker system and in the same component and only when I recieve a reply back I want to connect to the second broker. the most efficient and eay way to do this without adding complexity to the app and keep it simple is to just call cojject once I have thenreply back.

**Comment by kum-deepak** [comment]
In this case there is one more way to write it. I am assuming that you have stompConfig for the second broker handy when you are intending to connect.

```
// In your code where you want to connect
stompConfig2 = {'Your STOMP': 'config for second broker'}
secondConnection = new StompService(stompConfig2)
```

Basically the key is to avoid using Angular's dependency injection mechanism and create the instance like a regular JavaScript class. All the test cases included with the code work the same way.

The stompService also has a `disconnect` method which you might use if you are certain.

**Comment by pantonis** [comment]
OK

**Comment by kum-deepak** [comment]
Please check #32
