### ISSUE TITLE
Add virtual host

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#3]
Can you please add support for Virtual Host as rabbitmq support this functionality.

**Comment by pantonis** [comment]
I added this. How do I commit it?

**Comment by sjmf** [comment]
You can fork the stomp-js/ng2-stompjs repo to pantonis/ng2-stompjs by pressing the 'fork' button in GitHub. 

My approach would be to check this out your fork as a branch in your working copy (see e.g. [this stackoverflow post](https://stackoverflow.com/questions/9153598/how-do-i-fetch-a-branch-on-someone-elses-fork-on-github) for the commands), and merge your working copy's changes into it. Finally, push it back to GitHub and create a Pull Request on this repo.

**Comment by kum-deepak** [comment]
I am out of station and unable to work on this for about 10 days. Meanwhile, if you can open a Pull Request for your change that will be helpful.

Basically it is planned to support headers for connect, subscribe, and publish - these enable features like virtual host, auto/manual ack.

**Comment by pantonis** [comment]
sjmf I forked cloned the repo make a new branch (feature) push the branch on my forked repo. 
When I try to create a pull request on this repo (/stomp-js/ng2-stompjs) I dont see the branch I created on my forked repo

**Comment by pantonis** [comment]
Ok managed to do it!

**Comment by pantonis** [comment]
Ok I have also added headers. Since I am web noob and I dont know how to update npm packages can anyone please review and if everything is ok merge the pull requests and publish to npm.

**Comment by pantonis** [comment]
10 days? :worried: is there any slight small tiny chance that you can review it earlier? :)

**Comment by sjmf** [comment]
I'm happy to review, if @kum-deepak cannot – but I can't publish to npm.

If you want to use the npm package in the mean time, you can reference the git repo directly and npm can handle that:

```
npm install git+https://git@github.com/pantonis/ng2-stompjs.git
```

**Comment by pantonis** [comment]
@smjf Thanks a lot Sam. That did the trick

**Comment by kum-deepak** [comment]
Please check the latest release (0.3.x). The configuration now accepts headers, which can contain entry for host. Please note that way to provide user/password has changed.
