### ISSUE TITLE
Temp queues callback

### ISSUE THREAD

**Issue by bmm** [stomp-js/ng2-stompjs#30]
Hi,

Before the question I would like to thank you for the good work with this library.

I'm doing a RPC like implementation, I'm passing the reply-to header in the sending message. I also receive a log message saying that the reply message arrived, but that it was unhandled.
Is it possible to set a callback for temporary queues?

Thank you.

**Comment by kum-deepak** [comment]
:) Great to hear that you find this library useful.

The current released version of the library does not allow subscribing to the `default queue`.

I have been working on simplifying rpc service - especially when using with RabbitMQ. Please check the branch `rpc`.

It is not fully done yet, no documentation so far. Following is the key idea:

- You call the `rpc` method in `StompRPCService` - with parameters - `serviceEndPoint: string` and `payload: string`. You will get an Observable which will trigger on the response.
- It will internally set reply-to and co-relation ids.
- See the code in https://github.com/stomp-js/ng2-stompjs/blob/rpc/src/stomp-rpc.service.ts

Example:

```typescript
    const myServiceEndPoint = '/topic/echo';
    stompRPCService.rpc(myServiceEndPoint, 'Hello').subscribe((message: Message) => {
      // Use response
    });
```

See: https://github.com/stomp-js/ng2-stompjs/blob/rpc/src/specs/app/services/stomp-rpc.service.spec.ts for sample code (including a small rpc server endpoint).

On the server endpoint, you need to honor reply-to and co-relation id (which is same as examples at RabbitMQ website).

I had taken a task to create the most simple `rpc` service client out there. Your feedback will be valuable.

**Comment by kum-deepak** [comment]
Any further information?
