### ISSUE TITLE
After calling disconnect status stays 101

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#31]
I have a stomp service where on component's ngOnDestroy I call stompService.disconnect();

I can see that connection is chrome dev tools stays with status 101. Is this correct behavior

![image](https://user-images.githubusercontent.com/3295086/31820244-2681e2be-b5a9-11e7-8baa-bc0ea6aaac2e.png)

**Comment by sjmf** [comment]
I believe this is the correct behaviour. 101 is the status code sent in the header returned from the server to upgrade the HTTP connection to a websocket connection. 

Chrome isn't telling you anything about the ongoing connected status of the WS connection with this screenshot, only a historical view of the original upgrade response.

**Comment by pantonis** [comment]
How can I see that the ws connection was successfully disconnected?

**Comment by kum-deepak** [comment]
The disconnect and cleanup happens after the server returns DISCONNECTED frame as per STOMP standards. I have never checked in RabbitMQ if the active connection count drops.

It may be worth checking at RabbitMQ web UI to see if the connection count goes down. Can you please do it?

**Comment by pantonis** [comment]
@kum-deepak Yes indeed it is connection count goes down.
May I ask if connect/disconnect is very expensive operation?

**Comment by kum-deepak** [comment]
I don't think so. Both are one round trip each.

**Comment by pantonis** [comment]
ok thanks
