### ISSUE TITLE
packaging problem

### ISSUE THREAD

**Issue by cHullaert** [stomp-js/ng2-stompjs#33]
Hi,

When I'm trying to package my module using ng2-stompjs with  ng-packagr, I get the following error.

> BUILD ERROR
> Could not resolve './src/stomp.service' from node_modules/@ stomp/ng2-stompjs/index.ts
> Error: Could not resolve './src/stomp.service' from node_modules/@ stomp/ng2-stompjs/index.ts
>     at error (/home/christof/development/cover/components/socket-commands/node_modules/rollup/dist/rollup.js:185:14)
>     at then.resolvedId (/home/christof/development/cover/components/socket-commands/node_modules/rollup/dist/rollup.js:10062:8)

Any idea ?

**Comment by cHullaert** [comment]
I've to tried but it seems that if I change index.ts with following code, it works
```
export {StompService, StompState} from '@stomp/ng2-stompjs/src/stomp.service';
export {StompConfig} from '@stomp/ng2-stompjs/src/stomp.config';

```

**Comment by kum-deepak** [comment]
Does the packaged version work for you?

**Comment by cHullaert** [comment]
I get this message if I don't change
BUILD ERROR
Could not resolve './src/stomp.service' from node_modules/@stomp/ng2-stompjs/index.ts
Error: Could not resolve './src/stomp.service' from node_modules/@stomp/ng2-stompjs/index.ts
    at error (/home/christof/development/cover/components/command-bindings/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/home/christof/development/cover/components/command-bindings/node_modules/rollup/dist/rollup.js:10062:8)

**Comment by cHullaert** [comment]
I used the version get by NPM

**Comment by kum-deepak** [comment]
Moving to #38
