### ISSUE TITLE
Catching error

### ISSUE THREAD

**Issue by jwz104** [stomp-js/ng2-stompjs#35]
My `StompService` sends an `Authorization` header with a JWT token. But when the token is expired the server will return an error:
`<<< ERROR
message:Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is org.springframework.security.authentication.CredentialsExpiredException\c Provided token is expired
content-length:0`

Of course this is expected behavior. But I am not able to catch the error and the `StompService` won't reconnect after this error, it only reconnects when the web socket is interrupted.

I would like to catch the error so I can refresh the token. Is this possible?

**Comment by jwz104** [comment]
Error handling is now fixed, but it is still not possible to reconnect.

**Comment by kum-deepak** [comment]
Currently the reconnect is handled by the underlying library. That library tries to reconnect only when the underlying WebSocket connection drops. In other cases it does not.

Let me figure out some alternate way of reconnecting in case of errors.

**Comment by kum-deepak** [comment]
I was working on allowing manual config, in that process I have refactored the service to allow calls to multiple connects (with potentially updated configuration).

Please see #32 

Will love your feedback.
