### ISSUE TITLE
Package as compiled JS

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/ng2-stompjs#38]
Currently this library is distributed as ts files. We need to package it as compiled JS.

**Comment by Sabartius** [comment]
This package is really helpful, we use it for several internal libraries: https://github.com/dherges/ng-packagr

**Comment by kum-deepak** [comment]
I have done some work using https://github.com/dherges/ng-packagr , please follow branch `bin`. The binary package has not been tested fully yet. Please point to https://github.com/stomp-js/ng2-stompjs/releases/download/0.5.0-bin/stomp-ng2-stompjs-v0.5.0.tgz as your installation source.

The bundled version should be compatible for Angular 2, 4, and 5.

Once I have some success reports, I will make this part of the general release.

**Comment by Sabartius** [comment]
@kum-deepak I tried your package, it works with Angular 5 :)

**Comment by weichcri** [comment]
@kum-deepak your package worked fine, thanks ;)

**Comment by domkrel** [comment]
It works for me. ng-packagr did the job! @kum-deepak

**Comment by kum-deepak** [comment]
Great to hear! I will switch to this packaging soon, may be this weekend.

**Comment by pedroapy** [comment]
I read you are using ng-package, but just if this may be something useful for you, in this PR: https://github.com/stomp-js/ng2-stompjs/pull/39 I'm doing the code to generate a dist folder with necessary javascript code for distributing your library using gulp as the angular-material team does. Moreover, I'm removing all unnecessary dependencies like angular-cli.

**Comment by domkrel** [comment]
@kum-deepak I hope you will release it soon. In our company setup we can only use officially released npm packages.

**Comment by kum-deepak** [comment]
Released as 0.6.0, please try.

**Comment by kum-deepak** [comment]
If no further issue reported, I will close this issue in few days.
