### ISSUE TITLE
Disable console logging

### ISSUE THREAD

**Issue by tastyday** [stomp-js/ng2-stompjs#41]
I would like to be able to disable the websocket information that is logged in console because it is creating a lot of verbose output for my app and making it difficult to see other things in console. Everytime a new subscription message comes in I get an output of the payload and header details, etc. Is there a way to disable this?

**Comment by tastyday** [comment]
Oh nevermind I just commented out line 45 in stomp.service.js: console.log(new Date(), args);

**Comment by kum-deepak** [comment]
You should be able to pass `debug: false` in the configuration. Please raise a ticket if after setting this flag you are getting these logged into console.
