### ISSUE TITLE
Memory leak after upgrading to angular 5

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#50]
Hi 

I have updated my project to angular 5 and I am using ```"@stomp/ng2-stompjs": "0.6.0"```
I noticed memory leak. My scenario involves receiving data from server of 150KB each message every 2 seconds. I isolated memory leak to ng2-stompjs library. What I did was removed every other code and memory leak is present. Once I remove ng2-stompjs and reading the data from json file and refreshing it using a timer, memory leak goes away.

Thanks

**Comment by kum-deepak** [comment]
Please share a simple project that demonstrates the issue. Thanks!

**Comment by pantonis** [comment]
After thorough testing couldn't link this with Mem Leak
