### ISSUE TITLE
Can't send TextMessages

### ISSUE THREAD

**Issue by ahavriluk** [stomp-js/ng2-stompjs#52]
It seems there is a problem sending text messages to ActiveMQ broker. 
According to this  http://activemq.apache.org/stomp.html if content-length header is included it sends BytesMessage, if not - TextMessage. The content-length header is included by default. In order to exclude it it has to be defined like that 
this.stompService.publish(queueName, message,
    {
      ['content-length']:false
    });

because stomjs checks if it true/false:
skipContentLength = if (@headers['content-length'] == false) then true else false

It is not possible to set content-length to false because StompHeaders is defined like this:
export declare type StompHeaders = {
    [key: string]: string;
}
It must have string value.

**Comment by kum-deepak** [comment]
Pushed a version, changing the type to any. Please check against the master branch and let me know if it works correctly. Based on your confirmation I will release a new version.

**Comment by ahavriluk** [comment]
It skips the content-length header now. But I couldn't test if the received message is actually TextMessage. It would require a .Net client or Java. Neither is available at this moment to me. I leave it to you to test it completely.

**Comment by kum-deepak** [comment]
Thanks, in that case I will close this for now.
