### ISSUE TITLE
Reconnection also re-subscribe?

### ISSUE THREAD

**Issue by creativeprogramming** [stomp-js/ng2-stompjs#53]
It seems to me that in case of lost connection, the library can reconnect but cannot re-subscribe all the topics automatically, is this true?

**Comment by kum-deepak** [comment]
The library is supposed to reconnect all topics on successful re-connection. Please check when your re-connection issues are resolved.

**Comment by creativeprogramming** [comment]
Thanks for reply you can close this issue see #54
