### ISSUE TITLE
Reconnection seems to be not working

### ISSUE THREAD

**Issue by creativeprogramming** [stomp-js/ng2-stompjs#54]
If i restart my backend I get this output on the client:

```
Thu Feb 01 2018 15:02:59 GMT+0100 (CET) "Whoops! Lost connection to omissis/ws"
ng2-stompjs.es5.js:58 Thu Feb 01 2018 15:02:59 GMT+0100 (CET) "Error: Whoops! Lost connection to omissis/ws"
ng2-stompjs.es5.js:58 Thu Feb 01 2018 15:02:59 GMT+0100 (CET) "STOMP: scheduling reconnection in 5000ms"
ng2-stompjs.es5.js:58 Thu Feb 01 2018 15:03:04 GMT+0100 (CET) "STOMP: attempting to reconnect"
ng2-stompjs.es5.js:58 Thu Feb 01 2018 15:03:04 GMT+0100 (CET) "Opening Web Socket..."
```

But it stucks to this state: Opening Web Socket... no more info

**Comment by creativeprogramming** [comment]
I'm using SockJS

**Comment by kum-deepak** [comment]
Please check the instructions for using with SockJS here: https://stomp-js.github.io/ng2-stompjs/additional-documentation/sock-js.html

Kindly report if it does not help.

**Comment by creativeprogramming** [comment]
Thanks, it helped!

**Comment by kum-deepak** [comment]
Used this opportunity to update https://stomp-js.github.io/ng2-stompjs/additional-documentation/sock-js.html 

Also added a note in Readme pointing to this documentation.
