### ISSUE TITLE
Automatic re-connection persists after disconnect() is called

### ISSUE THREAD

**Issue by jokam85** [stomp-js/ng2-stompjs#58]
When server (broker) goes down, reconnect mechanism kicks in (if reconnect_delay > 0). If we call disconnect() during this period automatic re-connection does not stop. It still tries to connect to server even if we called disconnect() manually. 

This is the scenario:

1. broker is up and running
2. client connects with StompRService
3. broker goes down (eg. server restart)
4. we call disconnect on client side for some reason (eg. user logs off the system)
5. client still keeps reconnecting

**Comment by kum-deepak** [comment]
This was an issue with the underlying @stomp/stompjs library. This has been fixed there, but not released in npm yet. In couple of days, I will make a release of the other library to see if that fixes the issue.

**Comment by jokam85** [comment]
Thanks for fast response. This is very unpleasant bug because it causes huge number of reconnection requests to our server on restarts.

**Comment by jokam85** [comment]
This is our fix until we come up with more elegant solution.
On manual disconnect we explicitly turn off reconnection. Little bit dirty but at least it solves our
problem for now.

```typescript
export class WoStompRService extends StompRService {

  disconnect() {
    if (this.client) {
      this.client.reconnect_delay = 0;
    }
    super.disconnect();
  }
}
```

**Comment by kum-deepak** [comment]
Please update `@stomp/stompjs` to 4.0.2 and see if that resolves the issue.

**Comment by jokam85** [comment]
I tried it. Did not help :(

**Comment by kum-deepak** [comment]
I will be having another go at it. :)

**Comment by jokam85** [comment]
Did you try to reproduce my scenario?

**Comment by kum-deepak** [comment]
I think I know what is happening. The code inside the underlying library is quite old and needs refactoring to fix this.

Please use your workaround for now. I am little busy these days. So, will take little time.

**Comment by kum-deepak** [comment]
I have added following test case:

```typescript
  describe('should disconnect even when underlying connection is not there', () => {
    // Simulate error on Websocket and wait for while and call disconnect
    beforeEach((done) => {
      stompService.forceDisconnect();
      ensureStompDisconnected(stompService, done);
    });

    // Ask service to disconnect and wait for 2200 ms (more than double
    // of reconnect delay)
    beforeEach((done) => {
      stompService.disconnect();
      setTimeout(() => { done(); }, 2200);
    });

    it('and not reconnect', () => {
      expect(stompService.state.getValue()).toEqual(StompState.CLOSED);
    });

  });
```
Does this simulate your case?

This case fails with `@stomp/stompjs` lesser than `4.0.2`. Please tell me version of `@stomp/stompjs` that you are using?

If in doubt add the following to your package.json file and run `npm i` or `yarn` as the case may be:

```
"@stomp/stompjs": "^4.0.0 >=4.0.2"
```

**Comment by kum-deepak** [comment]
Otherwise please update to latest version of this library. it is dependency set to latest version of @stomp/stompjs, please let me know if it resolves the issue for you.

**Comment by jokam85** [comment]
I'm not sure if this test case simulates my scenario. Connection in my case was closed due to network outage or server down, not by calling .disconnect() method. After server or network failure, calling .disconnect() did not stop re-connection attempts.

**Comment by kum-deepak** [comment]
`stompService.forceDisconnect();` actually force closes the underlying WebSocket to simulate a connection error. It is not regular disconnect.

The test cases simulates an error and then calls `disconnect` and checks that it did not reconnect.

Please send me your console log messages after upgrading to latest version.

**Comment by jokam85** [comment]
OK that should simulate the case then. I will do as suggested as soon as possible

**Comment by kum-deepak** [comment]
Any further information?

**Comment by jokam85** [comment]
Sorry for taking me so long to respond. These are the current versions of library:

```
npm show @stomp/stompjs version
4.0.2

npm show @stomp/ng2-stompjs version
0.6.4
```
Problem is still present with these versions. It is still trying to reconnect even if .disconnect() is closed.

I'm not sure if this test is precise enough, because state really is CLOSED but it keeps trying to connect:
```javascript
it('and not reconnect', () => {
     expect(stompService.state.getValue()).toEqual(StompState.CLOSED);
});
````

**Comment by kum-deepak** [comment]
Auto reconnect logic is in the underlying library. Not sure what is going on. 

Please switch on debug and send me the console output.

**Comment by PhilippS93** [comment]
I am using this library too and I can confirm the issue with the reconnect. Btw, great work!

**Comment by kum-deepak** [comment]
Please set debug on and send me the console output. I hope that you are on the latest version.

**Comment by marcelormourao** [comment]
Automatic reconnection doesn't work to me. =(

**Comment by kum-deepak** [comment]
@marcelormourao I will suggest to check the following:

- Check `reconnect_delay` setting (https://github.com/stomp-js/ng2-stompjs#all-the-hard-work)
- Check (https://stomp-js.github.io/ng2-stompjs/additional-documentation/sock-js.html) if using ScokJS.

**Comment by marcelormourao** [comment]
@kum-deepak  Sorry! I was using SockJs. When I removed that, automatic reconnection works.

But, this workaround solves automatic reconnection problems with SockJs.
```
this._stompService.state
      .map((state: number) => StompState[state])
      .subscribe((status: string) => {
        console.log(`Stomp connection status: ${status}`);

        if (status === StompState[StompState.CLOSED]) {
          const socket = new SockJS(`...`);

          const stompClient: Stomp.Client = Stomp.over(socket);

          const headers = {};

          stompClient.connect(headers, (frame) => {
            this._stompService.client = stompClient;

            this._stompService.state.next(StompState.CONNECTED);
          }, (error) => {
            this._stompService.state.next(StompState.CLOSED);
          });

        }
      });
```

**Comment by kum-deepak** [comment]
@marcelormourao you do not need that round about way, please check https://stomp-js.github.io/ng2-stompjs/additional-documentation/sock-js.html

**Comment by kum-deepak** [comment]
Closing this issue as resolved.
