### ISSUE TITLE
StompService coupled to StompConfigService

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#6]
Hi,

StompService is coupled on StompConfigService which in my opinion is not good. In a large enterprise system where several vhosts/username/password are used the following problems might occur :
1. Creating a StompConfigService file for each StompService is redundant.
2. Values should not be hardcoded into ts file but instead into config files where compilation is not needed every time broker/connection settings change

**Comment by pantonis** [comment]
Any feedback on this?

**Comment by kum-deepak** [comment]
Not sure what is your point. The class StompConfigService is a mechanism to inject the configuration into the StompService.

- If you are using Angular with Webpack (which is the case if you are using Angular CLI), and you are keeping configuration in a file, a configuration change will trigger recompilation. 
- One way to keep configuration outside code is to fetch it using HTTP. https://github.com/stomp-js/ng2-stompjs-demo - shows an application where connection parameters are fetched using an HTTP call. Pay attention to https://github.com/stomp-js/ng2-stompjs-demo/blob/master/src/app/services/config/config.service.ts#L32 . This can be adjusted to point to your HTTP API that returns the configuration.
- https://angular.io/docs/ts/latest/guide/dependency-injection.html cover basics of Dependency Injection in Angular.
- By cleverly using Dependency Injection of Angular, it is possible to use multiple StompServices with different connection parameters. If this is your need, you will possibly need to spend time with: https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html

If you can be more specific about how you are planning to keep your configuration - within your code or outside your code, I might be able to offer further suggestions.

**Comment by pantonis** [comment]
Hi.

I want to keep configuration out of the code. Since I have several customers, configs should be in json files.

To further understand what I am trying to achieve see below

RootModule
|
|---AppModule
|	|---ClientsModule
		|---ClientAccountingStompService (settings: ClientsVirtualHost login:clientsAccounting)
		|---ClientDetailsStompService (settings: ClientsVirtualHost login:clientsDetails)
|	|---OrdersModule
		|---OrdersStompService (settings: OrdersVirtualHost login:12345)
|
|---ExtraNetModule
|	|---VendorsModule
|		|---StockStompService (settings: VendorsStockVirtualHost login:abcded)		
|	|----PostModule
|		|---CostStompService (settings: PostVirtualHost login:post)		

As you can see my software consists of several modules with submodules. Every module needs to have its own configuration (url, virtualhost, login, pass). I need each module to have its own config (json) file. As I mentioned above I have lots of clients so I need theses settings to be in json files. If I have them hardcoded in the code I will need to keep a branch for each client etc..

**Comment by kum-deepak** [comment]
Just to make sure that I understand correctly:
- You have a complex application that needs multiple Stomp Service instances (as per your screenshot 5).
- You have multiple customers, details for the above 5 connection depend on each customer.

Will it suffice if I write a small sample that instantiates 2 StompServices using 2 different JSON files fetched over HTTP?

**Comment by pantonis** [comment]
@kum-deepak Yes buddy. You are absolutely correct. 

A small sample of what you suggested would be good thanks.

**Comment by kum-deepak** [comment]
Give me sometime, :)

**Comment by pantonis** [comment]
ok

**Comment by kum-deepak** [comment]
Please see https://github.com/stomp-js/ng2-stomp-demo-multi

Go through the README. It is definitely advanced usage of Dependency Injection of Angular.

**Comment by pantonis** [comment]
Thanks for your example.
Seems to be what I was looking for except for the part that I need to pass the url as a parameter depending on the module I am.

Please see my committed example
https://github.com/pantonis/ng2-stomp-demo-multi.git

I have the case that I have shared components across different modules and each shared component has its own stomp config depending on the module is loaded.

e.g 

![image](https://cloud.githubusercontent.com/assets/3295086/25479059/40d537ca-2b4c-11e7-9c27-934eec139471.png)

**Comment by kum-deepak** [comment]
I do not think you will be able to use Angular's Dependency Injection framework to fully achieve what you need.

I have done another sample that shows how to bypasses Angular's Dependency Injection framework and create instances of StompServices with config given by a URL. 

It is in a new branch (raw-factory) in the previous sample:

- https://github.com/stomp-js/ng2-stomp-demo-multi/tree/raw-factory

It is possible to create few instances using this approach and few using Angular's Dependency Injection framework.

**Comment by pantonis** [comment]
What about the shared service?

How can I create an instance of it and use that when I load the rawData component which uses the comp1 inside it?

**Comment by kum-deepak** [comment]
I am assuming that current sample solves your issue with some of your cases where you need StompService with a specific configuration.

Now assuming that apart from those you need one (or more) StompService that will be used by many components and configuration for this remains the same once created. To cover this you can use the approach outlined in the master branch of the sample.

Both these techniques (master branch and raw-factory branch) can be used in the same application.

Just to understand your needs better, does both the techniques (master branch and raw-factory branch) put together cover your requirement?

**Comment by kum-deepak** [comment]
It might also help to create the instance of StompService that comp1 (src/app/shared/comp1/comp1.ts) needs gets created in constructor or OnInit handler of that component.

If there will many instances of this component, you may create the StompService in a Service class that you create with the StompService available as a public member.

I hope the above helps.

**Comment by pantonis** [comment]
I managed to do it using the 

```
providers: [{ provide: Comp1StompService, useClass: Comp1StompModuleAService}]

```

in the component I want to use it
