### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by pantonis** [stomp-js/ng2-stompjs#64]
Hi,

Is it possible to include release notes when a version is released? This is quite useful to identify what was changed.

**Comment by kum-deepak** [comment]
Thanks for the suggestion. Will include from next release.

**Comment by pantonis** [comment]
Can you tell the differences between 0.6.2 and 0.6.4 please?

**Comment by kum-deepak** [comment]
Please check https://stomp-js.github.io/ng2-stompjs/changelog.html

I have updated the README as well to include link to the change log.

**Comment by pantonis** [comment]
Thank you very much
