### ISSUE TITLE
The new reconnect connection will try to send all sent messages

### ISSUE THREAD

**Issue by vodanh109** [stomp-js/ng2-stompjs#65]
We're having a serious problem. The new connection after reconnecting, will send all sent messages again.

- To reproduce that:
+ Refresh web page to create a new WS connection
+ Try to send some messages
+ Disconnect Internet connection, wait for timeout then reconnect Internet again
+ The new WS Connection will be established, and then send all sent messages before

Please help us, because it's really serious. A lot of requests will be executed multiple times

**Comment by kum-deepak** [comment]
I see you have closed the issue, did you find a solution?

**Comment by vodanh109** [comment]
Yeap. The error come from our logic, not because of your library. We subscribe connectionobservable to send request without unsubscribing it. So every time when connection state is CONNECTED, it will resend again
