### ISSUE TITLE
Change the StompConfig dynamic 

### ISSUE THREAD

**Issue by tayler0101** [stomp-js/ng2-stompjs#72]
Hi,
i am trying to change the URL at some point after the program is running, i already start to set new config but it dose not work.
Any suggestions ?

thank you in advance.

**Comment by domkrel** [comment]
@tayler0101 did you find a solution?

**Comment by kum-deepak** [comment]
Currently there is no easy way to do this. You will have to create a new StompService if you need to change the URL.

I am currently working to refactor the underlying library (you can check https://github.com/stomp-js/stompjs/issues/2), one done I will update this library as well to support this.

**Comment by domkrel** [comment]
@kum-deepak thank you for the info. For my simple use case (build url depending on dynamic data) the StompRService was enough.

**Comment by tayler0101** [comment]
@domkrel i used StompRService,it is not ideal dynamic but it done the purpose.You should be aware  that StompRService stop or disconnect dosen't work as it should be,that is way i overwrite the disconnect function.

**Comment by tayler0101** [comment]
see #78
