### ISSUE TITLE
Q: Best way to re-subscribe after re-connection?

### ISSUE THREAD

**Issue by zapphyre** [stomp-js/ng2-stompjs#76]
Title say's it for itself.
When my server goes down and up, ng-stomp reconnects but does not subscribe back.
So what is a best option for me to do so? Any event to watch for?

Thanks!

**Comment by kum-deepak** [comment]
You can watch https://stomp-js.github.io/ng2-stompjs/injectables/StompRService.html#connectObservable to be notified of each successful connect.

Usually the subscriptions are restored when the underlying connection reestablishes. If you share a project where it does not subscribe back on reconnect, I will have a look.

**Comment by zapphyre** [comment]
You're right! I'm posting to the wrong repo. I was using ng2-stom-service.
Your's better, I have switched over. Everything works as should.
You can delete this, sorry&thanks!
