### ISSUE TITLE
Automatic re-connection persists after disconnect() is called reopen

### ISSUE THREAD

**Issue by tayler0101** [stomp-js/ng2-stompjs#78]
hi,
i would like to ask you if fixed this error: #58 
thank you

**Comment by kum-deepak** [comment]
Which version of Angular you are using?

**Comment by kum-deepak** [comment]
I have upgraded the underlying library `@stomp/stompjs` to `4.0.7`. Please force a dependency to that version in you `package.json`, I will suggest:

```JSON
{
  "dependencies": {
    "@stomp/stompjs": "^4.0.0 >=4.0.7"
  }
}
``` 

Let me know if it resolves the issue.

**Comment by tayler0101** [comment]
i am using ionic 3 with angular 5 and my version of ng2-stopmjs is 0.6.2

**Comment by tayler0101** [comment]
thank for your response, unfortuanlly it dosnt work, here is what i am tring to do:
-this.stompRService.config = this.bulidStompConfig();//5000 delay before reconnect
-this.stompRService.initAndConnect();
so if there is no connection established after 4 trying i want it to stop trying so i use:
this.stompRService.disconnect();
but it dosn't work
Thank in advance

**Comment by kum-deepak** [comment]
Please see #77, which is fundamentally the same issue.
