### ISSUE TITLE
How can I set subscribers durable/non durable

### ISSUE THREAD

**Issue by tatos85** [stomp-js/ng2-stompjs#80]
Hi
Is there any option to set a subscriber durable type?

**Comment by kum-deepak** [comment]
Not sure if I understand your query. Does the following answer your query:

https://stackoverflow.com/questions/27041500/rabbitmq-stomp-can-i-create-durable-queue-on-subscribe

**Comment by tatos85** [comment]
Hi, I'm sorry. I'll try to explain it better: 
I'm working with activemq, where you have two subscribers types: durable and non durable. I need to susbcribe with durable setting to a topic, can I do that with ng2-stompjs ?

Reference:
https://activemq.apache.org/stomp.html

**Comment by kum-deepak** [comment]
Based on the documentation link do you think setting `client-id` for `CONNECT` will make it durable?

If yes, you can add `client-id` to https://stomp-js.github.io/ng2-stompjs/injectables/StompConfig.html#headers and see if it works.
