### ISSUE TITLE
Reconnect Not working with Sock Js with Angular 6

### ISSUE THREAD

**Issue by spencerfontein** [stomp-js/ng2-stompjs#84]
import {StompConfig, StompService} from '@stomp/ng2-stompjs';
import * as SockJS from 'sockjs-client';

const socketProvider = new SockJS(`*.*.*.*:9081/test/test-websocket`);
`const stompConfig: StompConfig = {

  url: socketProvider,

    headers: {
    login: 'guest',
    passcode: 'guest'
  },

  heartbeat_in: 0, 
  heartbeat_out: 20000, 

  reconnect_delay: 5000,

  debug: true
};`

My Stomp Version: @stomp/ng2-stompjs": "^6.0.0

After the initial fail, It attempts to reconnect but just hangs there without failing.

**Comment by kum-deepak** [comment]
Please check instructions at https://github.com/stomp-js/ng2-stompjs#sockjs-users

**Comment by spencerfontein** [comment]
Thank you for your response, but that is where I got the code posted above from and it looks the same as what is at https://stomp-js.github.io/ng2-stompjs/additional-documentation/sock-js.html.

**Comment by spencerfontein** [comment]
Thank you that worked perfectly!

**Comment by spencerfontein** [comment]
and just FYI https://github.com/stomp-js/ng6-stompjs-demo/blob/master/src/app/app.module.ts on that the implementation of url is url: 'ws://127.0.0.1:15674/ws'
