### ISSUE TITLE
relative URL in Config

### ISSUE THREAD

**Issue by csabi81** [stomp-js/ng2-stompjs#86]
Is there a way to use a relative URL, not specifying the server itself, which will be configured by a proxy .
Not I got a simple syntax error:

SyntaxError: Failed to construct 'WebSocket': The URL '/notificationService/notificationSocket' is invalid.

I what to avoid specifying the server as it can be different on development and deploy.

I think setting the server in proxy (I use for development node, ngnix and apache reverse proxy on deploy) is not difficult but what I think is that the component itself checks for correct syntax so a ws: must be specified.

**Comment by kum-deepak** [comment]
The WebSocket expects an absolute URL. You may construct absolute URL using `window.location.href` to avoid hard coding it.

**Comment by kum-deepak** [comment]
Also check https://developer.mozilla.org/en-US/docs/Web/API/URL/URL
