### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by acSpock** [stomp-js/ng2-stompjs#9]
I'm running angular 4.0.0. and the latest ng-stomp 0.3.5 with webpack and am getting the following unexpected token export when I load the application in the browser.  Obviously export is es6 only 
```
	export { StompService, StompState } from './src/stomp.service'; 
	export { StompConfigService } from './src/stomp-config.service';
```

Any help debugging this issue to get it to compile correctly?

**Comment by kum-deepak** [comment]
Can you please provide the following details:

- Which file(s) are causing these errors?
- Did you check the sample - https://github.com/stomp-js/ng4-stompjs-demo?
- Are you using AngularCLI?
- If you are unable to solve, will it be possible for you to share a cut down version of your application which shows this error.

I must say Angular2 module packaging is still a mystery for me. :)

**Comment by acSpock** [comment]
Sure 
1. It looks like it's the index.js file in the @stomp/ng2-stompjs/index.js
2. I did check and followed it exactly.
3. I am using webpack to compile. Not using angular CLI.
4. I will share a cutdown

**Comment by kum-deepak** [comment]
Will it be possible for you to share a cut down version of the project which shows this issue?

**Comment by kum-deepak** [comment]
Closing this for lack of response.

**Comment by remohy1** [comment]
I am having the same problem when running  ./node_modules/.bin/ngu-sw-manifest. If you still can look into this, I can provide code

**Comment by kum-deepak** [comment]
Please open a new issue. Sample code that demonstrates the issue will definitely be helpful
