### ISSUE TITLE
Test support for binary messages

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/ng2-stompjs#97]

**Comment by pantonis** [comment]
@kum-deepak I will test the binary messages. just want to know which version of ng2-stompjs supports this?

**Comment by pantonis** [comment]
ok!

**Comment by kum-deepak** [comment]
I have released 7.0.0-beta.4 which is feature complete and no known issues.

Migration guide at: https://stomp-js.github.io/guide/ng2-stompjs/2018/11/05/migrate-ng2-stompjs-v7.html

Tutorial at: https://stomp-js.github.io/guide/ng2-stompjs/2018/11/04/ng2-stomp-with-angular7.html

**Comment by kum-deepak** [comment]
Version 7.0.0 has been released.
